/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChildTableGrid: typeof import('./src/components/ChildTableGrid.vue')['default']
    DocumentLayoutEditor: typeof import('./src/components/DocumentLayoutEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShellLayout: typeof import('./src/components/ShellLayout.vue')['default']
    TableMultiSelectField: typeof import('./src/components/TableMultiSelectField.vue')['default']
    WorkspaceLayout: typeof import('./src/components/WorkspaceLayout.vue')['default']
  }
}
