/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionPanel: typeof import('./src/components/ActionPanel.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    RecordDetail: typeof import('./src/components/RecordDetail.vue')['default']
    RecordList: typeof import('./src/components/RecordList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShellLayout: typeof import('./src/components/ShellLayout.vue')['default']
  }
}
