import {
	ArrowRight,
	CloudDownload,
	CreditCard,
	Database,
	Globe2,
	LayoutDashboard,
	Layers3,
	Package,
	GitBranch,
	RefreshCcw,
	Server,
	Settings2,
	Pause,
	ShieldAlert,
	SquareArrowOutUpRight,
	Store,
	ListChecks,
	Users,
	UserRound,
	AlertTriangle,
	CircleHelp,
	ScrollText,
	Sparkles,
} from 'lucide-vue-next'

const linkField = (options, labelFields = []) => ({ type: 'link', options, labelFields })
const submittedLinkField = (options, labelFields = []) => ({ ...linkField(options, labelFields), targetIsSubmittable: true })
const selectField = (options) => ({ type: 'select', options })
const checkField = { type: 'check' }

const activeStatusOptions = ['Active', 'Inactive']
const releasePolicyOptions = ['Manual', 'Quality First', 'Production Eligible', 'LTS']
const buildStatusOptions = ['Draft', 'Queued', 'Running', 'Succeeded', 'Failed', 'Cancelled']
const releaseStatusOptions = ['Draft', 'Built', 'Quality', 'Production Eligible', 'Blocked', 'Retired']
const rolloutEligibilityOptions = ['Not Eligible', 'Quality Only', 'Production Eligible', 'Blocked']
const clusterProviderOptions = ['Hcloud', 'AWS', 'Local', 'Other']
const clusterEnvironmentOptions = ['Development', 'Staging', 'Production']
const clusterStatusOptions = ['Draft', 'Active', 'Maintenance', 'Disabled', 'Retired']
const healthStatusOptions = ['Unknown', 'Healthy', 'Degraded', 'Failed']
const benchStatusOptions = ['Draft', 'Pending', 'Accepted', 'Provisioning', 'Ready', 'Upgrading', 'Suspended', 'Deletion Requested', 'Quiescing', 'Deleting', 'Deleted', 'Deletion Failed', 'Failed', 'Retired', 'Unknown']
const upgradePolicyOptions = ['Manual', 'Scheduled', 'Auto Quality', 'Auto Production Eligible']
const upgradeSopStatusOptions = ['Draft', 'Scheduled', 'Precheck', 'Ready', 'Running', 'Verifying', 'Completed', 'Rolled Back', 'Failed']
const siteStatusOptions = ['Draft', 'Requested', 'Accepted', 'Provisioning', 'Ready', 'Active', 'Suspended', 'Deletion Requested', 'Quiescing', 'Deleting', 'Deletion Failed', 'Failed', 'Deleted', 'Unknown']
const provisioningStatusOptions = ['Not Started', 'Pending', 'Accepted', 'Running', 'Ready', 'Deletion Requested', 'Quiescing', 'Deleting', 'Deleted', 'Deletion Failed', 'Failed', 'Unknown']
const backupStateOptions = ['Not Configured', 'Scheduled', 'Running', 'Succeeded', 'Failed']
const restoreStateOptions = ['Not Requested', 'Pending', 'Running', 'Succeeded', 'Failed']
const upgradeStateOptions = ['Not Scheduled', 'Scheduled', 'Running', 'Verifying', 'Succeeded', 'Failed']
const regionDeploymentOptions = ['Not Deployable', 'Active', 'Maintenance', 'Disabled']
const planStatusOptions = ['Active', 'Inactive', 'Retired']
const benchPolicyOptions = ['Shared Bench', 'Dedicated Bench', 'Manual Placement']
const integrationStatusOptions = ['Not Configured', 'Configured', 'Healthy', 'Degraded', 'Disabled']
const databaseStatusOptions = ['Draft', 'Pending', 'Provisioning', 'Ready', 'Maintenance', 'Deletion Requested', 'Quiescing', 'Deleting', 'Deleted', 'Deletion Failed', 'Failed', 'Unknown']
const databaseProvisioningOptions = ['Not Started', 'Pending', 'Accepted', 'Running', 'Ready', 'Deletion Requested', 'Quiescing', 'Deleting', 'Deleted', 'Deletion Failed', 'Failed', 'Unknown']
const databaseProvisioningTypeOptions = ['Operator Managed', 'External']
const routeStatusOptions = ['Not Checked', 'Pending', 'Ready', 'Failed', 'Unknown']
const tlsStatusOptions = ['Inherited', 'Ready', 'Failed', 'Unknown']
const hostnameStatusOptions = ['Pending', 'Reserved', 'Conflict', 'Released']
const edgeStatusOptions = ['Unknown', 'Ready', 'Degraded', 'Failed']

const runtimeNamespaceOptionFields = ['namespace', 'cluster', 'region', 'customer', 'runtime_purpose', 'status', 'approved_for_platform', 'is_default']
const runtimeNamespacePurposeAllowsPrivacy = (purpose, privacy) => {
	if (!purpose || !privacy) return true
	if (purpose === 'enterprise') return ['Private', 'Private Shared'].includes(privacy)
	return {
		public: ['Public'],
		'private-shared': ['Private Shared'],
		private: ['Private'],
	}[purpose]?.includes(privacy) ?? true
}
const runtimeNamespaceOptionFilter = (row, model = {}, resourceKey = '') => {
	if (row.name === 'default') {
		return resourceKey === 'database-servers' && model.operator_resource_name === 'frappe-mariadb'
	}
	if (row.status !== 'Active' || !Number(row.approved_for_platform || 0)) return false
	if (row.region && model.region && row.region !== model.region) return false
	if (!runtimeNamespacePurposeAllowsPrivacy(row.runtime_purpose, model.privacy)) return false
	const namespaceCustomer = row.customer
	const selectedCustomer = model.owner_customer || model.customer || model.privacy_boundary
	if (namespaceCustomer && selectedCustomer && namespaceCustomer !== selectedCustomer) return false
	if (namespaceCustomer && ['Private', 'Private Shared'].includes(model.privacy || '') && !selectedCustomer) return false
	return true
}
const runtimeNamespaceField = (description) => ({
	...linkField('Runtime Namespace', ['namespace', 'runtime_purpose', 'customer', 'region', 'status']),
	optionFields: runtimeNamespaceOptionFields,
	optionFilter: runtimeNamespaceOptionFilter,
	description,
})

export const platformResources = [
	{
		key: 'customers',
		scope: 'platform',
		label: 'Customers',
		doctype: 'Customer',
		route: '/platform/customers',
		detailRoute: (name) => `/platform/customers/${encodeURIComponent(name)}`,
		icon: Users,
		listHelp: 'Customer records, identity links, and primary region placement.',
		summaryFields: [
			{ key: 'first_name', label: 'First name' },
			{ key: 'last_name', label: 'Last name' },
			{ key: 'region', label: 'Primary region', linkPrefix: '/platform/regions/', ...linkField('Region') },
			{ key: 'external_customer_id', label: 'External ID' },
		],
		detailFields: [
			{ key: 'name', label: 'Customer ID' },
			{ key: 'first_name', label: 'First name' },
			{ key: 'last_name', label: 'Last name' },
			{ key: 'user', label: 'User' },
			{ key: 'region', label: 'Primary region', linkPrefix: '/platform/regions/', ...linkField('Region') },
			{ key: 'external_customer_id', label: 'External ID' },
		],
		actions: [
			{
				key: 'request-site',
				label: 'Request site',
				icon: SquareArrowOutUpRight,
				description: 'Capture a new site request in the UI. Backend creation support is not wired yet.',
				backendSupported: false,
				fields: [
					{ key: 'company_name', label: 'Company name', type: 'text', placeholder: 'Acme Incorporated' },
					{ key: 'preferred_region', label: 'Preferred region', placeholder: 'us-east', ...linkField('Region') },
					{ key: 'preferred_release_group', label: 'Preferred release group', placeholder: '2026.06', ...linkField('Release Group') },
					{ key: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Describe the request and rollout constraints.' },
				],
			},
		],
	},
	{
		key: 'customer-members',
		scope: 'platform',
		label: 'Customer Members',
		doctype: 'Customer Member',
		route: '/platform/customer-members',
		detailRoute: (name) => `/platform/customer-members/${encodeURIComponent(name)}`,
		icon: UserRound,
		creatable: true,
		editable: true,
		listHelp: 'Customer access memberships created by signup, domain matching, invites, or Platform operators.',
		lifecycleFields: [
			{ key: 'customer', label: 'Customer', required: true, ...linkField('Customer', ['first_name', 'last_name', 'organization_name']) },
			{ key: 'user', label: 'User', required: true, ...linkField('User', ['full_name', 'email']) },
			{ key: 'member_role', label: 'Role', default: 'Member', ...selectField(['Owner', 'Admin', 'Member', 'Viewer']) },
			{ key: 'status', label: 'Status', default: 'Pending', ...selectField(['Active', 'Pending', 'Disabled']) },
			{ key: 'source', label: 'Source', default: 'Platform', ...selectField(['Signup', 'Domain Match', 'Invite', 'Platform']) },
			{ key: 'is_primary_owner', label: 'Primary owner', ...checkField },
		],
		summaryFields: [
			{ key: 'customer', label: 'Customer', ...linkField('Customer', ['first_name', 'last_name', 'organization_name']) },
			{ key: 'user', label: 'User', ...linkField('User', ['full_name', 'email']) },
			{ key: 'member_role', label: 'Role', ...selectField(['Owner', 'Admin', 'Member', 'Viewer']) },
			{ key: 'status', label: 'Status', ...selectField(['Active', 'Pending', 'Disabled']) },
			{ key: 'source', label: 'Source', ...selectField(['Signup', 'Domain Match', 'Invite', 'Platform']) },
		],
		detailFields: [
			{ key: 'name', label: 'Membership' },
			{ key: 'customer', label: 'Customer', ...linkField('Customer', ['first_name', 'last_name', 'organization_name']) },
			{ key: 'user', label: 'User', ...linkField('User', ['full_name', 'email']) },
			{ key: 'member_role', label: 'Role', ...selectField(['Owner', 'Admin', 'Member', 'Viewer']) },
			{ key: 'status', label: 'Status', ...selectField(['Active', 'Pending', 'Disabled']) },
			{ key: 'source', label: 'Source', ...selectField(['Signup', 'Domain Match', 'Invite', 'Platform']) },
			{ key: 'is_primary_owner', label: 'Primary owner', ...checkField },
			{ key: 'approved_by', label: 'Approved by', ...linkField('User', ['full_name', 'email']) },
			{ key: 'approved_on', label: 'Approved on', type: 'datetime' },
		],
		actions: [],
	},

	{
		key: 'release-groups',
		scope: 'platform',
		label: 'Release Groups',
		doctype: 'Release Group',
		route: '/platform/release-groups',
		detailRoute: (name) => `/platform/release-groups/${encodeURIComponent(name)}`,
		icon: Layers3,
		listHelp: 'Release group is master data for a product/image family. Deployable versions live in Release.',
		creatable: true,
		editable: true,
		lifecycleFields: [
			{ key: 'title', label: 'Title', required: true },
			{ key: 'status', label: 'Status', default: 'Active', ...selectField(activeStatusOptions) },
			{ key: 'registry_url', label: 'Registry URL' },
			{ key: 'image_repository', label: 'Image repository' },
			{ key: 'supported_frappe_major_version', label: 'Supported Frappe major' },
			{ key: 'release_policy', label: 'Release policy', default: 'Manual', ...selectField(releasePolicyOptions) },
			{ key: 'apps_metadata', label: 'Apps metadata', type: 'textarea' },
		],
		summaryFields: [
			{ key: 'title', label: 'Title' },
			{ key: 'status', label: 'Status', ...selectField(activeStatusOptions) },
			{ key: 'registry_url', label: 'Registry URL' },
			{ key: 'image_repository', label: 'Image repository' },
		],
		detailFields: [
			{ key: 'name', label: 'Release group ID' },
			{ key: 'title', label: 'Title' },
			{ key: 'status', label: 'Status', ...selectField(activeStatusOptions) },
			{ key: 'registry_url', label: 'Registry URL' },
			{ key: 'image_repository', label: 'Image repository' },
			{ key: 'included_apps', label: 'Included apps' },
			{ key: 'apps_metadata', label: 'Apps metadata' },
			{ key: 'supported_frappe_major_version', label: 'Supported Frappe major' },
			{ key: 'release_policy', label: 'Release policy', ...selectField(releasePolicyOptions) },
		],
		actions: [
			{
				key: 'create-release',
				label: 'Create release',
				icon: ArrowRight,
				description: 'Release creation is a platform workflow. Backend pipeline creation remains a gap until wired.',
				backendSupported: false,
				fields: [
					{ key: 'image_tag', label: 'Image tag', type: 'text', placeholder: 'v2026.06.1' },
					{ key: 'pipeline_reference', label: 'Pipeline reference', type: 'text', placeholder: 'CI build URL or ID' },
					{ key: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Release intent and compatibility notes.' },
				],
			},
		],
	},
	{
		key: 'apps',
		scope: 'platform',
		label: 'Apps',
		doctype: 'App',
		route: '/platform/apps',
		detailRoute: (name) => `/platform/apps/${encodeURIComponent(name)}`,
		icon: Package,
		listHelp: 'Application master data used by Release Groups through the Included Apps table multiselect.',
		creatable: true,
		editable: true,
		lifecycleFields: [
			{ key: 'title', label: 'Title', required: true },
			{ key: 'repository_url', label: 'Repository URL' },
		],
		summaryFields: [
			{ key: 'title', label: 'Title' },
			{ key: 'repository_url', label: 'Repository URL' },
		],
		detailFields: [
			{ key: 'name', label: 'App ID' },
			{ key: 'title', label: 'Title' },
			{ key: 'repository_url', label: 'Repository URL' },
		],
		actions: [],
	},
	{
		key: 'releases',
		scope: 'platform',
		label: 'Releases',
		doctype: 'Release',
		route: '/platform/releases',
		detailRoute: (name) => `/platform/releases/${encodeURIComponent(name)}`,
		icon: GitBranch,
		listHelp: 'Release is the transactional deployable image/version inside a Release Group.',
		creatable: true,
		editable: true,
		submittable: true,
		lifecycleFields: [
			{ key: 'release_group', label: 'Release group', required: true, ...linkField('Release Group') },
			{ key: 'image_tag', label: 'Image tag', required: true },
			{ key: 'image_digest', label: 'Image digest' },
			{ key: 'build_status', label: 'Build status', default: 'Draft', ...selectField(buildStatusOptions) },
			{ key: 'build_pipeline_reference', label: 'Build/pipeline reference' },
			{ key: 'release_status', label: 'Release status', default: 'Draft', ...selectField(releaseStatusOptions) },
			{ key: 'rollout_eligibility', label: 'Rollout eligibility', default: 'Not Eligible', ...selectField(rolloutEligibilityOptions) },
			{ key: 'build_date', label: 'Build date', type: 'datetime' },
			{ key: 'promoted_date', label: 'Promoted date', type: 'datetime' },
			{ key: 'release_notes', label: 'Changelog / release notes', type: 'textarea' },
			{ key: 'compatibility_notes', label: 'Compatibility notes', type: 'textarea' },
		],
		summaryFields: [
			{ key: 'release_group', label: 'Release group', linkPrefix: '/platform/release-groups/', ...linkField('Release Group') },
			{ key: 'image_tag', label: 'Image tag' },
			{ key: 'build_status', label: 'Build status', ...selectField(buildStatusOptions) },
			{ key: 'release_status', label: 'Release status', ...selectField(releaseStatusOptions) },
			{ key: 'rollout_eligibility', label: 'Rollout eligibility', ...selectField(rolloutEligibilityOptions) },
			{ key: 'docstatus', label: 'Docstatus' },
		],
		detailFields: [
			{ key: 'name', label: 'Release ID' },
			{ key: 'release_group', label: 'Release group', linkPrefix: '/platform/release-groups/', ...linkField('Release Group') },
			{ key: 'image_tag', label: 'Image tag' },
			{ key: 'image_digest', label: 'Image digest' },
			{ key: 'build_status', label: 'Build status', ...selectField(buildStatusOptions) },
			{ key: 'build_pipeline_reference', label: 'Build/pipeline reference' },
			{ key: 'release_status', label: 'Release status', ...selectField(releaseStatusOptions) },
			{ key: 'build_date', label: 'Build date', type: 'datetime' },
			{ key: 'promoted_date', label: 'Promoted date', type: 'datetime' },
			{ key: 'release_notes', label: 'Changelog / release notes' },
			{ key: 'compatibility_notes', label: 'Compatibility notes' },
			{ key: 'rollout_eligibility', label: 'Rollout eligibility', ...selectField(rolloutEligibilityOptions) },
		],
		actions: [
			{
				key: 'promote-release',
				label: 'Promote release',
				icon: ArrowRight,
				description: 'Promotion is exposed as a UI entry point. Pipeline/operator execution remains a backend gap.',
				backendSupported: false,
				fields: [
					{ key: 'target_status', label: 'Target status', placeholder: 'Quality or Production Eligible', ...selectField(releaseStatusOptions) },
					{ key: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Promotion notes and expected impact.' },
				],
			},
		],
	},
	{
		key: 'clusters',
		scope: 'platform',
		label: 'Clusters',
		doctype: 'Cluster',
		route: '/platform/clusters',
		detailRoute: (name) => `/platform/clusters/${encodeURIComponent(name)}`,
		icon: Server,
		listHelp: 'Registered runtime targets. Regions choose the active Cluster used for Bench and Site placement.',
		creatable: true,
		editable: true,
		lifecycleFields: [
			{ key: 'title', label: 'Title', required: true },
			{ key: 'cluster_name', label: 'Cluster name', required: true },
			{ key: 'region', label: 'Region', ...linkField('Region') },
			{ key: 'provider', label: 'Provider', default: 'Hcloud', ...selectField(clusterProviderOptions) },
			{ key: 'environment', label: 'Environment', default: 'Development', ...selectField(clusterEnvironmentOptions) },
			{ key: 'status', label: 'Status', default: 'Active', ...selectField(clusterStatusOptions) },
			{ key: 'manager_host', label: 'Manager host' },
			{ key: 'headlamp_url', label: 'Headlamp URL' },
			{ key: 'operator_namespace', label: 'Operator namespace', default: 'frappe-operator-system' },
			{ key: 'default_storage_class', label: 'Default storage class', default: 'local-path' },
			{ key: 'default_bench_namespace_pattern', label: 'Default bench namespace pattern', default: 'bench-{bench}' },
			{ key: 'kubeconfig_reference', label: 'Kubeconfig reference' },
			{ key: 'credential_reference', label: 'Credential reference' },
			{ key: 'domain_strategy', label: 'Domain strategy', default: 'Wildcard', ...selectField(['Wildcard', 'Custom Domains']) },
			{ key: 'ingress_class', label: 'Ingress class', default: 'traefik' },
			{ key: 'wildcard_hostname', label: 'Wildcard hostname' },
		],
		summaryFields: [
			{ key: 'cluster_name', label: 'Cluster name' },
			{ key: 'region', label: 'Region', linkPrefix: '/platform/regions/', ...linkField('Region') },
			{ key: 'provider', label: 'Provider', ...selectField(clusterProviderOptions) },
			{ key: 'status', label: 'Status', ...selectField(clusterStatusOptions) },
			{ key: 'health_status', label: 'Health', ...selectField(healthStatusOptions) },
		],
		detailFields: [
			{ key: 'name', label: 'Cluster ID' },
			{ key: 'cluster_name', label: 'Cluster name' },
			{ key: 'region', label: 'Region', linkPrefix: '/platform/regions/', ...linkField('Region') },
			{ key: 'provider', label: 'Provider', ...selectField(clusterProviderOptions) },
			{ key: 'environment', label: 'Environment', ...selectField(clusterEnvironmentOptions) },
			{ key: 'status', label: 'Status', ...selectField(clusterStatusOptions) },
			{ key: 'manager_host', label: 'Manager host' },
			{ key: 'manager_public_ip', label: 'Manager public IP' },
			{ key: 'manager_private_ip', label: 'Manager private IP' },
			{ key: 'headlamp_url', label: 'Headlamp URL' },
			{ key: 'access_method', label: 'Access method' },
			{ key: 'operator_namespace', label: 'Operator namespace' },
			{ key: 'default_runtime_namespace', label: 'Default runtime namespace' },
			{ key: 'default_storage_class', label: 'Default storage class' },
			{ key: 'default_bench_namespace_pattern', label: 'Default bench namespace pattern' },
			{ key: 'kubeconfig_reference', label: 'Kubeconfig reference' },
			{ key: 'credential_reference', label: 'Credential reference' },
			{ key: 'domain_strategy', label: 'Domain strategy', ...selectField(['Wildcard', 'Custom Domains']) },
			{ key: 'wildcard_hostname', label: 'Wildcard hostname' },
			{ key: 'wildcard_dns_status', label: 'Wildcard DNS', readOnly: true, ...selectField(edgeStatusOptions) },
			{ key: 'wildcard_tls_status', label: 'Wildcard TLS', readOnly: true, ...selectField(edgeStatusOptions) },
			{ key: 'ingress_status', label: 'Ingress', readOnly: true, ...selectField(edgeStatusOptions) },
			{ key: 'ingress_class', label: 'Ingress class' },
			{ key: 'health_status', label: 'Health status', ...selectField(healthStatusOptions) },
			{ key: 'last_sync_time', label: 'Last sync' },
			{ key: 'last_error', label: 'Last error' },
		],
		actions: [
			{
				key: 'sync-runtime-namespaces',
				label: 'Sync runtime namespaces',
				icon: RefreshCcw,
				description: 'Create or update Runtime Namespace records from Kubernetes namespace discovery, falling back to the configured runtime namespace when list is denied.',
				backendSupported: true,
				method: 'lenscloud.api.orchestration.sync_runtime_namespaces',
				paramsFromRecord: { cluster: 'name' },
				fields: [],
			},
			{
				key: 'validate-cluster-gates',
				label: 'Validate cluster gates',
				icon: ShieldAlert,
				description: 'Run server-side Platform readiness gates through the Python Kubernetes client before live apply is enabled.',
				backendSupported: true,
				method: 'lenscloud.api.orchestration.validate_cluster_readiness',
				paramsFromRecord: { cluster: 'name' },
				fields: [
					{ key: 'expected_root_domain', label: 'Expected root domain', type: 'text', default: 'testcloud.lmnaslens.com' },
					{ key: 'database_server', label: 'Dry-run Database Server', ...linkField('Database Server', ['title', 'privacy', 'region']) },
					{ key: 'bench', label: 'Dry-run Bench', ...linkField('Bench', ['title', 'region']) },
					{ key: 'site', label: 'Dry-run Site', ...linkField('Site', ['title', 'subdomain']) },
				],
			},
		],
	},
	{
		key: 'runtime-namespaces',
		scope: 'platform',
		label: 'Runtime Namespaces',
		doctype: 'Runtime Namespace',
		route: '/platform/runtime-namespaces',
		detailRoute: (name) => `/platform/runtime-namespaces/${encodeURIComponent(name)}`,
		icon: Server,
		listHelp: 'Cluster-approved Kubernetes namespaces synced from Infra-created runtime targets. Platform selects these; it does not create Kubernetes namespaces.',
		creatable: false,
		editable: false,
		summaryFields: [
			{ key: 'namespace', label: 'Namespace' },
			{ key: 'cluster', label: 'Cluster', linkPrefix: '/platform/clusters/', ...linkField('Cluster', ['title', 'cluster_name']) },
			{ key: 'status', label: 'Status', ...selectField(['Active', 'Unavailable', 'Unknown']) },
			{ key: 'runtime_purpose', label: 'Purpose', ...selectField(['public', 'private-shared', 'private', 'enterprise']) },
			{ key: 'customer', label: 'Customer', linkPrefix: '/platform/customers/', ...linkField('Customer', ['first_name', 'last_name']) },
			{ key: 'approved_for_platform', label: 'Approved', ...checkField },
			{ key: 'verification_status', label: 'Verification', ...selectField(['Unknown', 'Verified', 'Pending', 'Failed']) },
			{ key: 'is_default', label: 'Default', ...checkField },
		],
		detailFields: [
			{ key: 'name', label: 'Runtime Namespace ID' },
			{ key: 'namespace', label: 'Namespace' },
			{ key: 'cluster', label: 'Cluster', linkPrefix: '/platform/clusters/', ...linkField('Cluster', ['title', 'cluster_name']) },
			{ key: 'status', label: 'Status', ...selectField(['Active', 'Unavailable', 'Unknown']) },
			{ key: 'source', label: 'Source', ...selectField(['Kubernetes Namespace List', 'Cluster Runtime Probe', 'Infra Handoff', 'Manual']) },
			{ key: 'region', label: 'Region', linkPrefix: '/platform/regions/', ...linkField('Region') },
			{ key: 'customer', label: 'Customer', linkPrefix: '/platform/customers/', ...linkField('Customer', ['first_name', 'last_name']) },
			{ key: 'runtime_purpose', label: 'Runtime purpose', ...selectField(['public', 'private-shared', 'private', 'enterprise']) },
			{ key: 'cluster_label', label: 'Infra cluster label' },
			{ key: 'approved_for_platform', label: 'Approved for Platform', ...checkField },
			{ key: 'verification_status', label: 'Verification status', ...selectField(['Unknown', 'Verified', 'Pending', 'Failed']) },
			{ key: 'verification_message', label: 'Verification message' },
			{ key: 'is_default', label: 'Default runtime namespace', ...checkField },
			{ key: 'last_sync_time', label: 'Last sync' },
			{ key: 'last_error', label: 'Last sync warning' },
		],
		actions: [],
	},
	{
		key: 'database-servers',
		scope: 'platform',
		label: 'Database Servers',
		doctype: 'Database Server',
		route: '/platform/database-servers',
		detailRoute: (name) => `/platform/database-servers/${encodeURIComponent(name)}`,
		icon: Database,
		listHelp: 'MariaDB runtime capacity with Region, privacy, ownership, readiness, and Bench attachment policy.',
		creatable: true,
		editable: true,
		lifecycleFields: [
			{ key: 'title', label: 'Title', required: true },
			{ key: 'database_engine', label: 'Database engine', default: 'MariaDB', ...selectField(['MariaDB']) },
			{ key: 'provisioning_type', label: 'Provisioning type', default: 'Operator Managed', ...selectField(databaseProvisioningTypeOptions) },
			{ key: 'region', label: 'Region', required: true, ...linkField('Region') },
			{ key: 'privacy', label: 'Privacy', required: true, ...linkField('Privacy') },
			{ key: 'owner_customer', label: 'Owner Customer', ...linkField('Customer', ['first_name', 'last_name']) },
			{ key: 'privacy_boundary', label: 'Privacy boundary' },
			{ key: 'kubernetes_namespace', label: 'Runtime namespace', ...runtimeNamespaceField('Select an active approved Runtime Namespace. Options are filtered by Region, customer, purpose, and privacy. Only protected frappe-mariadb may use default.') },
			{ key: 'operator_resource_name', label: 'MariaDB resource name', required: true },
			{ key: 'image', label: 'MariaDB image', default: 'mariadb:10.11' },
			{ key: 'storage_class', label: 'Storage class', default: 'local-path' },
			{ key: 'storage_size', label: 'Storage size', default: '8Gi' },
			{
				key: 'data_retention_policy',
				label: 'Data retention policy',
				default: 'Retain',
				description: 'Retain preserves owned database PVCs after Database Server deletion. Delete requires owned PVC cleanup before deletion completes.',
				...selectField(['Retain', 'Delete']),
			},
			{ key: 'replica_count', label: 'Replica count', default: 1, type: 'number' },
			{ key: 'root_credential_secret_reference', label: 'Root Secret reference' },
			{ key: 'maximum_bench_count', label: 'Maximum Bench count', default: 0, type: 'number' },
		],
		summaryFields: [
			{ key: 'region', label: 'Region', linkPrefix: '/platform/regions/', ...linkField('Region') },
			{ key: 'privacy', label: 'Privacy', ...linkField('Privacy') },
			{ key: 'database_status', label: 'Database status', ...selectField(databaseStatusOptions) },
			{ key: 'health_status', label: 'Health', ...selectField(healthStatusOptions) },
			{ key: 'attached_bench_count', label: 'Benches' },
		],
		detailFields: [
			{ key: 'name', label: 'Database Server ID' },
			{ key: 'title', label: 'Title' },
			{ key: 'database_engine', label: 'Database engine', ...selectField(['MariaDB']) },
			{ key: 'provisioning_type', label: 'Provisioning type', ...selectField(databaseProvisioningTypeOptions) },
			{ key: 'region', label: 'Region', linkPrefix: '/platform/regions/', ...linkField('Region') },
			{ key: 'cluster', label: 'Cluster', readOnly: true, linkPrefix: '/platform/clusters/', ...linkField('Cluster') },
			{ key: 'privacy', label: 'Privacy', ...linkField('Privacy') },
			{ key: 'owner_customer', label: 'Owner Customer', linkPrefix: '/platform/customers/', ...linkField('Customer', ['first_name', 'last_name']) },
			{ key: 'privacy_boundary', label: 'Privacy boundary' },
			{ key: 'kubernetes_namespace', label: 'Runtime namespace', linkPrefix: '/platform/runtime-namespaces/', ...runtimeNamespaceField('Select an active approved Runtime Namespace. Options are filtered by Region, customer, purpose, and privacy.') },
			{ key: 'operator_resource_name', label: 'MariaDB resource name' },
			{ key: 'image', label: 'MariaDB image' },
			{ key: 'storage_class', label: 'Storage class' },
			{ key: 'storage_size', label: 'Storage size' },
			{
				key: 'data_retention_policy',
				label: 'Data retention policy',
				description: 'Retain preserves owned database PVCs after Database Server deletion. Delete requires owned PVC cleanup before deletion completes.',
				...selectField(['Retain', 'Delete']),
			},
			{ key: 'replica_count', label: 'Replica count', type: 'number' },
			{ key: 'root_credential_secret_reference', label: 'Root Secret reference' },
			{ key: 'maximum_bench_count', label: 'Maximum Bench count', type: 'number' },
			{ key: 'attached_bench_count', label: 'Attached Benches', readOnly: true },
			{ key: 'database_status', label: 'Database status', readOnly: true, ...selectField(databaseStatusOptions) },
			{ key: 'provisioning_status', label: 'Provisioning status', readOnly: true, ...selectField(databaseProvisioningOptions) },
			{ key: 'health_status', label: 'Health status', readOnly: true, ...selectField(healthStatusOptions) },
			{ key: 'last_sync_time', label: 'Last sync', readOnly: true },
			{ key: 'last_error', label: 'Last error', readOnly: true },
		],
		actions: [
			{ key: 'dry-run-database-server', label: 'Preview MariaDB manifest', icon: SquareArrowOutUpRight, description: 'Generate a secret-safe MariaDB Operator manifest.', backendSupported: true, method: 'lenscloud.api.orchestration.dry_run_database_server_manifest', paramsFromRecord: { database_server: 'name' }, fields: [] },
			{ key: 'reconcile-database-server', label: 'Reconcile Database Server', icon: RefreshCcw, description: 'Idempotently apply when restricted Kubernetes access and apply are enabled; otherwise returns a dry-run.', backendSupported: true, method: 'lenscloud.api.orchestration.reconcile_database_server', paramsFromRecord: { database_server: 'name' }, fields: [{ key: 'dry_run', label: 'Dry run', ...checkField }] },
			{ key: 'sync-database-server', label: 'Sync runtime status', icon: RefreshCcw, description: 'Read MariaDB runtime readiness from Kubernetes.', backendSupported: true, method: 'lenscloud.api.orchestration.sync_database_server_status', paramsFromRecord: { database_server: 'name' }, fields: [] },
			{ key: 'inspect-database-server', label: 'Inspect runtime', icon: ScrollText, description: 'Show secret-safe MariaDB CR, finalizer, related workload, PVC, Service, Ingress, Job, and warning Event state.', backendSupported: true, method: 'lenscloud.api.orchestration.inspect_database_server_runtime', paramsFromRecord: { database_server: 'name' }, fields: [] },
			{ key: 'delete-database-server', label: 'Delete Database Server', icon: AlertTriangle, description: 'Delete only a platform-owned runtime MariaDB after all Benches are absent. Type the exact document name to confirm.', backendSupported: true, method: 'lenscloud.api.orchestration.delete_database_server', paramsFromRecord: { database_server: 'name' }, fields: [{ key: 'confirmation', label: 'Confirm document name', type: 'text' }, { key: 'reason', label: 'Reason', type: 'textarea' }] },
			{ key: 'retry-database-server-delete', label: 'Retry delete', icon: RefreshCcw, description: 'Retry a failed Database Server lifecycle delete after correcting the blocker.', backendSupported: true, method: 'lenscloud.api.orchestration.retry_lifecycle_delete', paramsFromRecord: { name: 'name' }, fields: [{ key: 'doctype', label: 'DocType', type: 'select', options: ['Database Server'], default: 'Database Server' }, { key: 'confirmation', label: 'Confirm document name', type: 'text' }] },
		],
	},
	{
		key: 'benches',
		scope: 'platform',
		label: 'Benches',
		doctype: 'Bench',
		route: '/platform/benches',
		detailRoute: (name) => `/platform/benches/${encodeURIComponent(name)}`,
		icon: Server,
		listHelp: 'Bench records group runtime capacity by Release Group, current Release, next Release, and operator target.',
		creatable: true,
		editable: true,
		lifecycleFields: [
			{ key: 'title', label: 'Title', required: true },
			{ key: 'release_group', label: 'Release group', required: true, ...linkField('Release Group') },
			{ key: 'current_release', label: 'Current Release', required: true, ...linkField('Release', ['image_tag', 'release_group']) },
			{ key: 'next_release', label: 'Next Release', ...linkField('Release', ['image_tag', 'release_group']) },
			{ key: 'region', label: 'Region', required: true, ...linkField('Region') },
			{ key: 'privacy', label: 'Privacy', ...linkField('Privacy') },
			{ key: 'owner_customer', label: 'Owner Customer', ...linkField('Customer', ['first_name', 'last_name']) },
			{ key: 'privacy_boundary', label: 'Privacy boundary' },
			{ key: 'database_server', label: 'Database Server', required: true, ...linkField('Database Server', ['title', 'privacy', 'region']) },
			{ key: 'kubernetes_namespace', label: 'Runtime namespace', linkPrefix: '/platform/runtime-namespaces/', ...runtimeNamespaceField('Select an active approved Runtime Namespace. Options are filtered by Region, customer, purpose, and privacy.') },
			{ key: 'operator_resource_name', label: 'Operator resource name' },
			{ key: 'storage_class', label: 'Storage class' },
			{ key: 'bench_status', label: 'Bench status', default: 'Draft', ...selectField(benchStatusOptions) },
			{ key: 'upgrade_window', label: 'Upgrade schedule/window' },
			{ key: 'upgrade_policy', label: 'Upgrade policy', default: 'Manual', ...selectField(upgradePolicyOptions) },
		],
		summaryFields: [
			{ key: 'title', label: 'Title' },
			{ key: 'release_group', label: 'Release group', linkPrefix: '/platform/release-groups/', ...linkField('Release Group') },
			{ key: 'cluster', label: 'Cluster', linkPrefix: '/platform/clusters/', ...linkField('Cluster', ['title', 'cluster_name']) },
			{ key: 'current_release', label: 'Current release', linkPrefix: '/platform/releases/', ...linkField('Release', ['image_tag', 'release_group']) },
			{ key: 'next_release', label: 'Next release', linkPrefix: '/platform/releases/', ...linkField('Release', ['image_tag', 'release_group']) },
			{ key: 'bench_status', label: 'Bench status', ...selectField(benchStatusOptions) },
		],
		detailFields: [
			{ key: 'name', label: 'Bench ID' },
			{ key: 'title', label: 'Title' },
			{ key: 'release_group', label: 'Release group', linkPrefix: '/platform/release-groups/', ...linkField('Release Group') },
			{ key: 'current_release', label: 'Current release', linkPrefix: '/platform/releases/', ...linkField('Release', ['image_tag', 'release_group']) },
			{ key: 'next_release', label: 'Next release', linkPrefix: '/platform/releases/', ...linkField('Release', ['image_tag', 'release_group']) },
			{ key: 'region', label: 'Region', linkPrefix: '/platform/regions/', ...linkField('Region') },
			{ key: 'cluster', label: 'Cluster', linkPrefix: '/platform/clusters/', ...linkField('Cluster', ['title', 'cluster_name']) },
			{ key: 'privacy', label: 'Privacy', ...linkField('Privacy') },
			{ key: 'owner_customer', label: 'Owner Customer', linkPrefix: '/platform/customers/', ...linkField('Customer', ['first_name', 'last_name']) },
			{ key: 'privacy_boundary', label: 'Privacy boundary' },
			{ key: 'database_server', label: 'Database Server', linkPrefix: '/platform/database-servers/', ...linkField('Database Server', ['title', 'privacy', 'region']) },
			{ key: 'cluster_runtime_target', label: 'Cluster/runtime target' },
			{ key: 'kubernetes_namespace', label: 'Runtime namespace', linkPrefix: '/platform/runtime-namespaces/', ...runtimeNamespaceField('Select an active approved Runtime Namespace. Options are filtered by Region, customer, purpose, and privacy.') },
			{ key: 'operator_resource_name', label: 'Operator resource name' },
			{ key: 'storage_class', label: 'Storage class' },
			{ key: 'bench_status', label: 'Bench status', ...selectField(benchStatusOptions) },
			{ key: 'upgrade_window', label: 'Upgrade schedule/window' },
			{ key: 'upgrade_policy', label: 'Upgrade policy', ...selectField(upgradePolicyOptions) },
			{ key: 'upgrade_sop_status', label: 'Upgrade/SOP status', ...selectField(upgradeSopStatusOptions) },
		],
		actions: [
			{
				key: 'dry-run-bench',
				label: 'Dry-run FrappeBench',
				icon: SquareArrowOutUpRight,
				description: 'Generate the operator FrappeBench manifest from Region-derived Cluster, Release, and Bench fields. No Kubernetes apply is performed.',
				backendSupported: true,
				method: 'lenscloud.api.orchestration.dry_run_bench_manifest',
				paramsFromRecord: { bench: 'name' },
				fields: [],
			},
			{
				key: 'reconcile-bench-dry-run',
				label: 'Reconcile bench dry-run',
				icon: RefreshCcw,
				description: 'Run the safe Bench reconcile path. Kubernetes apply remains disabled unless backend credentials and settings are later wired.',
				backendSupported: true,
				method: 'lenscloud.api.orchestration.reconcile_bench',
				paramsFromRecord: { bench: 'name' },
				fields: [{ key: 'dry_run', label: 'Dry run', ...checkField }],
			},
			{ key: 'sync-bench', label: 'Sync runtime status', icon: RefreshCcw, description: 'Read FrappeBench status from the selected Cluster.', backendSupported: true, method: 'lenscloud.api.orchestration.sync_bench_status', paramsFromRecord: { bench: 'name' }, fields: [] },
			{ key: 'inspect-bench', label: 'Inspect runtime', icon: ScrollText, description: 'Show secret-safe FrappeBench CR, finalizer, related workload, PVC, Service, Ingress, Job, and warning Event state.', backendSupported: true, method: 'lenscloud.api.orchestration.inspect_bench_runtime', paramsFromRecord: { bench: 'name' }, fields: [] },
			{ key: 'delete-bench', label: 'Delete bench', icon: AlertTriangle, description: 'Delete only a platform-owned Bench after dependent Sites are Deleted. Type the exact document name to confirm.', backendSupported: true, method: 'lenscloud.api.orchestration.delete_bench', paramsFromRecord: { bench: 'name' }, fields: [{ key: 'confirmation', label: 'Confirm document name', type: 'text' }, { key: 'reason', label: 'Reason', type: 'textarea' }] },
			{ key: 'retry-bench-delete', label: 'Retry delete', icon: RefreshCcw, description: 'Retry a failed Bench lifecycle delete after correcting the blocker.', backendSupported: true, method: 'lenscloud.api.orchestration.retry_lifecycle_delete', paramsFromRecord: { name: 'name' }, fields: [{ key: 'doctype', label: 'DocType', type: 'select', options: ['Bench'], default: 'Bench' }, { key: 'confirmation', label: 'Confirm document name', type: 'text' }] },
			{
				key: 'upgrade-bench',
				label: 'Upgrade bench',
				icon: RefreshCcw,
				description: 'Run the app-aware bench.update path after every active Site on this Bench is Scheduled and tested.',
				backendSupported: true,
				method: 'lenscloud.api.bench_command.run_bench_update',
				paramsFromRecord: { bench: 'name' },
				fields: [
					{ key: 'timeout_seconds', label: 'Timeout seconds', type: 'number', default: 1800 },
				],
			},
			{
				key: 'retire-bench',
				label: 'Retire bench',
				icon: ShieldAlert,
				description: 'Retirement is represented in the UI; backend execution is not wired yet.',
				backendSupported: false,
				fields: [
					{ key: 'reason', label: 'Reason', type: 'textarea', placeholder: 'Explain the retirement request.' },
				],
			},
		],
	},
	{
		key: 'sites',
		scope: 'platform',
		label: 'Sites',
		doctype: 'Site',
		route: '/platform/sites',
		detailRoute: (name) => `/platform/sites/${encodeURIComponent(name)}`,
		icon: Globe2,
		listHelp: 'Tenant instances inside benches, tied to customers and runtime placement.',
		creatable: true,
		editable: true,
		lifecycleFields: [
			{ key: 'customer', label: 'Customer', ...linkField('Customer', ['first_name', 'last_name']) },
			{ key: 'bench', label: 'Bench', required: true, ...linkField('Bench') },
			{ key: 'region', label: 'Region', required: true, ...linkField('Region') },
			{ key: 'plan', label: 'Plan', ...linkField('Plan', ['title', 'plan_code']) },
			{ key: 'subdomain', label: 'Subdomain', required: true },
			{ key: 'site_status', label: 'Site status', default: 'Draft', ...selectField(siteStatusOptions) },
			{ key: 'provisioning_status', label: 'Provisioning status', default: 'Not Started', ...selectField(provisioningStatusOptions) },
			{ key: 'operator_resource_name', label: 'Operator resource name' },
			{ key: 'hostname_reservation_status', label: 'Hostname reservation', default: 'Pending', ...selectField(hostnameStatusOptions) },
		],
		summaryFields: [
			{ key: 'title', label: 'Title' },
			{ key: 'domain', label: 'Domain' },
			{ key: 'site_status', label: 'Site status', ...selectField(siteStatusOptions) },
			{ key: 'cluster', label: 'Cluster', linkPrefix: '/platform/clusters/', ...linkField('Cluster', ['title', 'cluster_name']) },
			{ key: 'provisioning_status', label: 'Provisioning', ...selectField(provisioningStatusOptions) },
			{ key: 'route_status', label: 'Access route', ...selectField(routeStatusOptions) },
		],
		detailFields: [
			{ key: 'name', label: 'Site ID' },
			{ key: 'title', label: 'Title', readOnly: true },
			{ key: 'customer', label: 'Customer', linkPrefix: '/platform/customers/', ...linkField('Customer', ['first_name', 'last_name']) },
			{ key: 'bench', label: 'Bench', linkPrefix: '/platform/benches/', ...linkField('Bench') },
			{ key: 'region', label: 'Region', linkPrefix: '/platform/regions/', ...linkField('Region') },
			{ key: 'cluster', label: 'Cluster', linkPrefix: '/platform/clusters/', ...linkField('Cluster', ['title', 'cluster_name']) },
			{ key: 'plan', label: 'Plan', linkPrefix: '/platform/plans/', ...linkField('Plan', ['title', 'plan_code']) },
			{ key: 'subdomain', label: 'Subdomain' },
			{ key: 'domain', label: 'Domain', readOnly: true },
			{ key: 'site_status', label: 'Site status', ...selectField(siteStatusOptions) },
			{ key: 'provisioning_status', label: 'Provisioning status', ...selectField(provisioningStatusOptions) },
			{ key: 'operator_resource_name', label: 'Operator resource name' },
			{ key: 'hostname_reservation_status', label: 'Hostname reservation', readOnly: true, ...selectField(hostnameStatusOptions) },
			{ key: 'route_status', label: 'Route status', readOnly: true, ...selectField(routeStatusOptions) },
			{ key: 'tls_status', label: 'TLS status', readOnly: true, ...selectField(tlsStatusOptions) },
			{ key: 'access_url', label: 'Access URL', readOnly: true },
			{ key: 'last_route_check', label: 'Last route check', readOnly: true },
			{ key: 'route_error', label: 'Route error', readOnly: true },
			{ key: 'backup_state', label: 'Backup state', ...selectField(backupStateOptions) },
			{ key: 'restore_state', label: 'Restore state', ...selectField(restoreStateOptions) },
			{ key: 'upgrade_state', label: 'Upgrade state', ...selectField(upgradeStateOptions) },
			{ key: 'site_capability_state', label: 'Site Capability State', readOnly: true },
		],
		actions: [
			{
				key: 'dry-run-site',
				label: 'Dry-run FrappeSite',
				icon: SquareArrowOutUpRight,
				description: 'Generate the operator FrappeSite manifest. No Kubernetes apply is performed.',
				backendSupported: true,
				method: 'lenscloud.api.orchestration.dry_run_site_manifest',
				paramsFromRecord: { site: 'name' },
				fields: [],
			},
			{ key: 'reconcile-site', label: 'Reconcile Site', icon: RefreshCcw, description: 'Idempotently apply the FrappeSite and Traefik wildcard route when restricted access is enabled.', backendSupported: true, method: 'lenscloud.api.orchestration.reconcile_site', paramsFromRecord: { site: 'name' }, fields: [{ key: 'dry_run', label: 'Dry run', ...checkField }] },
			{ key: 'sync-site', label: 'Sync provisioning and access', icon: RefreshCcw, description: 'Read operator status and verify the HTTPS route.', backendSupported: true, method: 'lenscloud.api.orchestration.sync_site_status', paramsFromRecord: { site: 'name' }, fields: [] },
			{ key: 'sync-site-capability-state', label: 'Sync Capability State', icon: RefreshCcw, description: 'Refresh read-only Site Capability State from Subscription Capability records and command results.', backendSupported: true, method: 'lenscloud.api.capability.sync_site_capability_state', paramsFromRecord: { site: 'name' }, fields: [] },
			{ key: 'install-site-capability', label: 'Install Capability', icon: Sparkles, description: 'Fulfill a Subscription Capability onto this Site through the app-aware runtime-image install path.', backendSupported: true, method: 'lenscloud.api.bench_command.install_site_capability', paramsFromRecord: { site: 'name' }, fields: [{ key: 'subscription_capability', label: 'Subscription Capability', ...linkField('Subscription Capability', ['capability', 'status']) }, { key: 'timeout_seconds', label: 'Timeout seconds', type: 'number', default: 900 }] },
			{ key: 'install-bootstrap-apps', label: 'Install Bootstrap Apps', icon: Package, description: 'Install Release Group apps marked Install At Site Creation. Intended for provisioning recovery before customer handoff.', backendSupported: true, method: 'lenscloud.api.bench_command.install_site_bootstrap_apps', paramsFromRecord: { site: 'name' }, fields: [{ key: 'timeout_seconds', label: 'Timeout seconds', type: 'number', default: 900 }] },
			{ key: 'inspect-site', label: 'Inspect runtime', icon: ScrollText, description: 'Show secret-safe FrappeSite CR, finalizer, related workload, PVC, Service, Ingress, Job, and warning Event state.', backendSupported: true, method: 'lenscloud.api.orchestration.inspect_site_runtime', paramsFromRecord: { site: 'name' }, fields: [] },
			{
				key: 'configure-oauth',
				label: 'Configure OAuth',
				icon: RefreshCcw,
				description: 'Create or reuse the Platform OAuth Client and configure the target Site Social Login Key through the secret-safe Bench Command runner.',
				backendSupported: true,
				method: 'lenscloud.api.bench_command.configure_site_oauth',
				paramsFromRecord: { site: 'name' },
				fields: [
					{ key: 'timeout_seconds', label: 'Timeout seconds', type: 'number', default: 300 },
					{ key: 'reason', label: 'Reason', type: 'textarea', placeholder: 'Why is OAuth being configured for this Site?' },
				],
			},
			{
				key: 'site-control-command',
				label: 'Run Site Control command',
				icon: ScrollText,
				description: 'Run an approved Bench Command Job/API action for this Site. Maintenance mode, developer mode, approved site_config, and CORS use the Infra runner; backup, restore, Bench Test trigger, and LATP remain Unsupported.',
				backendSupported: true,
				method: 'lenscloud.api.bench_command.run_site_control_command',
				paramsFromRecord: { site: 'name' },
				fields: [
					{ key: 'command', label: 'Command', type: 'select', default: 'bench_test.status', options: ['bench_test.status', 'maintenance_mode.status', 'maintenance_mode.enable', 'maintenance_mode.disable', 'developer_mode.status', 'developer_mode.enable', 'developer_mode.disable', 'site_config.get', 'site_config.set', 'site_config.unset', 'cors.allowlist.get', 'cors.allowlist.update', 'backup.status', 'site_setup.status', 'site_setup.complete', 'oauth.status', 'backup.create', 'restore.preview', 'restore.execute', 'restore.status', 'bench_test.trigger', 'latp.status', 'latp.trigger'] },
					{ key: 'args', label: 'Args JSON', type: 'textarea', default: '{"mode":"status"}', placeholder: '{"mode":"status"}' },
					{ key: 'timeout_seconds', label: 'Timeout seconds', type: 'number', default: 60 },
					{ key: 'reason', label: 'Reason', type: 'textarea', placeholder: 'Why is this Site Control command being run?' },
				],
			},
			{
				key: 'create-site',
				label: 'Create site',
				icon: SquareArrowOutUpRight,
				description: 'Site creation is shown as a UI flow while the backend contract is still pending.',
				backendSupported: false,
				fields: [
					{ key: 'company_name', label: 'Company name', type: 'text', placeholder: 'Acme Incorporated' },
					{ key: 'target_region', label: 'Target region', placeholder: 'us-east', ...linkField('Region') },
					{ key: 'target_bench', label: 'Target bench', placeholder: 'bench-us-east-01', ...linkField('Bench') },
					{ key: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Any placement or migration constraints.' },
				],
			},
			{
				key: 'suspend-site',
				label: 'Suspend site',
				icon: Pause,
				description: 'Suspension is surfaced here, but the actual state transition remains a backend gap.',
				backendSupported: false,
				fields: [
					{ key: 'reason', label: 'Reason', type: 'textarea', placeholder: 'Why is the site being suspended?' },
				],
			},
			{
				key: 'delete-site',
				label: 'Delete site',
				icon: AlertTriangle,
				description: 'Delete only the exact platform-owned FrappeSite owner CR. Type the exact document name to confirm.',
				backendSupported: true,
				method: 'lenscloud.api.orchestration.delete_site',
				paramsFromRecord: { site: 'name' },
				fields: [
					{ key: 'confirmation', label: 'Confirm document name', type: 'text' },
					{ key: 'reason', label: 'Reason', type: 'textarea', placeholder: 'Explain the deletion request.' },
				],
			},
			{ key: 'retry-site-delete', label: 'Retry delete', icon: RefreshCcw, description: 'Retry a failed Site lifecycle delete after correcting the blocker.', backendSupported: true, method: 'lenscloud.api.orchestration.retry_lifecycle_delete', paramsFromRecord: { name: 'name' }, fields: [{ key: 'doctype', label: 'DocType', type: 'select', options: ['Site'], default: 'Site' }, { key: 'confirmation', label: 'Confirm document name', type: 'text' }] },
			{
				key: 'backup-site',
				label: 'Backup site',
				icon: CloudDownload,
				description: 'Backup request entry point is present in the UI; backend dispatch remains a gap.',
				backendSupported: false,
				fields: [
					{ key: 'label', label: 'Backup label', type: 'text', placeholder: 'nightly-2026-06-01' },
					{ key: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Retention or restore intent.' },
				],
			},
			{
				key: 'restore-site',
				label: 'Restore site',
				icon: Database,
				description: 'Restore entry point exists in the UI; backend execution is not implemented here.',
				backendSupported: false,
				fields: [
					{ key: 'backup_name', label: 'Backup name', type: 'text', placeholder: 'latest backup label' },
					{ key: 'target_time', label: 'Target time', type: 'text', placeholder: 'optional timestamp' },
					{ key: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Restore intent and constraints.' },
				],
			},
			{
				key: 'upgrade-site',
				label: 'Upgrade site',
				icon: RefreshCcw,
				description: 'Upgrade entry point is a UI-only control until the orchestration backend lands.',
				backendSupported: false,
				fields: [
					{ key: 'target_release', label: 'Target Release', placeholder: 'Release document name', ...linkField('Release', ['image_tag', 'release_group']) },
					{ key: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Expected impact and timing.' },
				],
			},
		],
	},
	{
		key: 'regions',
		scope: 'platform',
		label: 'Regions',
		doctype: 'Region',
		route: '/platform/regions',
		detailRoute: (name) => `/platform/regions/${encodeURIComponent(name)}`,
		icon: Globe2,
		listHelp: 'Placement hierarchy for region-aware and environment-aware workflows.',
		tree: {
			parentField: 'parent_region',
			groupField: 'is_group',
			orderBy: 'lft asc',
			extraFields: ['lft', 'rgt'],
		},
		listLimit: 200,
		summaryFields: [
			{ key: 'title', label: 'Title' },
			{ key: 'parent_region', label: 'Parent region', linkPrefix: '/platform/regions/', ...linkField('Region') },
			{ key: 'cluster', label: 'Cluster', linkPrefix: '/platform/clusters/', ...linkField('Cluster', ['title', 'cluster_name']) },
			{ key: 'deployment_status', label: 'Deployment status', ...selectField(regionDeploymentOptions) },
			{ key: 'is_group', label: 'Group', ...checkField },
		],
		detailFields: [
			{ key: 'name', label: 'Region ID' },
			{ key: 'title', label: 'Title' },
			{ key: 'parent_region', label: 'Parent region', linkPrefix: '/platform/regions/', ...linkField('Region') },
			{ key: 'cluster', label: 'Cluster', linkPrefix: '/platform/clusters/', ...linkField('Cluster', ['title', 'cluster_name']) },
			{ key: 'deployment_status', label: 'Deployment status', ...selectField(regionDeploymentOptions) },
			{ key: 'is_group', label: 'Group', ...checkField },
		],
		actions: [],
	},

	{
		key: 'plans',
		scope: 'platform',
		label: 'Plans',
		doctype: 'Plan',
		route: '/platform/plans',
		detailRoute: (name) => `/platform/plans/${encodeURIComponent(name)}`,
		icon: Package,
		listHelp: 'Commercial plan master data. Free plan enables first customer self-service site requests.',
		creatable: true,
		editable: true,
		lifecycleFields: [
			{ key: 'title', label: 'Title', required: true },
			{ key: 'plan_code', label: 'Plan code', required: true },
			{ key: 'status', label: 'Status', default: 'Active', ...selectField(planStatusOptions) },
			{ key: 'is_default', label: 'Is default', ...checkField },
			{ key: 'is_free', label: 'Is free', ...checkField },
			{ key: 'release_group', label: 'Release Group', ...linkField('Release Group', ['title']) },
			{ key: 'landscape', label: 'Landscape', ...linkField('Landscape', ['title']) },
			{ key: 'allowed_privacy_profiles', label: 'Allowed Privacy Profiles', type: 'table', description: 'Submitted Privacy Profiles customers may receive through this Plan.', columns: [{ key: 'privacy', label: 'Privacy Profile', required: true, ...submittedLinkField('Privacy Profile', ['title', 'privacy']) }] },
			{ key: 'default_privacy_profile', label: 'Default Privacy Profile', ...submittedLinkField('Privacy Profile', ['title', 'privacy']) },
			{ key: 'availability', label: 'Availability', default: 'Invite Only', ...selectField(['Public','Beta','Invite Only','Retired']) },
			{ key: 'subscription_limit', label: 'Subscription limit', default: '1', type: 'number' },
			{ key: 'monthly_price', label: 'Monthly price', default: '0' },
			{ key: 'site_limit', label: 'Site limit', default: '1' },
			{ key: 'bench_policy', label: 'Bench policy', default: 'Shared Bench', ...selectField(benchPolicyOptions) },
			{ key: 'billing_system_reference', label: 'Billing system reference' },
			{ key: 'description', label: 'Description', type: 'textarea' },
		],
		summaryFields: [
			{ key: 'title', label: 'Title' },
			{ key: 'plan_code', label: 'Plan code' },
			{ key: 'status', label: 'Status', ...selectField(planStatusOptions) },
			{ key: 'is_free', label: 'Free' },
			{ key: 'is_default', label: 'Default' },
		],
		detailFields: [
			{ key: 'name', label: 'Plan ID' },
			{ key: 'title', label: 'Title' },
			{ key: 'plan_code', label: 'Plan code' },
			{ key: 'status', label: 'Status', ...selectField(planStatusOptions) },
			{ key: 'is_default', label: 'Is default', ...checkField },
			{ key: 'is_free', label: 'Is free', ...checkField },
			{ key: 'release_group', label: 'Release Group' }, { key: 'landscape', label: 'Landscape' }, { key: 'allowed_privacy_profiles', label: 'Allowed Privacy Profiles' }, { key: 'default_privacy_profile', label: 'Default Privacy Profile' }, { key: 'availability', label: 'Availability' }, { key: 'subscription_limit', label: 'Subscription limit' },
			{ key: 'monthly_price', label: 'Monthly price' },
			{ key: 'site_limit', label: 'Site limit' },
			{ key: 'bench_policy', label: 'Bench policy', ...selectField(benchPolicyOptions) },
			{ key: 'billing_system_reference', label: 'Billing system reference' },
			{ key: 'description', label: 'Description' },
		],
		actions: [],
	},
	{
		key: 'subscriptions', scope: 'platform', label: 'Subscriptions', doctype: 'Subscription', route: '/platform/subscriptions',
		detailRoute: (name) => `/platform/subscriptions/${encodeURIComponent(name)}`, icon: Users,
		listHelp: 'Customer Plan enrollment, approval, policy snapshot, and environment lifecycle.',
		summaryFields: [
			{ key: 'customer', label: 'Customer', ...linkField('Customer', ['first_name', 'last_name']) },
			{ key: 'plan', label: 'Plan', ...linkField('Plan', ['title']) },
			{ key: 'region', label: 'Region', ...linkField('Region', ['title']) },
			{ key: 'status', label: 'Status' },
		],
		detailFields: [
			{ key: 'name', label: 'Subscription' }, { key: 'customer', label: 'Customer' }, { key: 'plan', label: 'Plan' },
			{ key: 'region', label: 'Region' }, { key: 'release_group', label: 'Release Group' }, { key: 'landscape', label: 'Landscape' },
			{ key: 'privacy_profile', label: 'Privacy Profile' }, { key: 'status', label: 'Status' }, { key: 'policy_hash', label: 'Policy version' },
		], relations: [], actions: [],
	},
	{
		key: 'environments', scope: 'platform', label: 'Environments', doctype: 'Environment', route: '/platform/environments',
		detailRoute: (name) => `/platform/environments/${encodeURIComponent(name)}`, icon: Layers3, creatable: true, editable: true,
		listHelp: 'Stable Dev, QA, Pre-Prod, and Prod deployment classifications.',
		lifecycleFields: [
			{ key: 'title', label: 'Title', required: true }, { key: 'code', label: 'Code', required: true },
			{ key: 'deployment_tier', label: 'Deployment Tier', ...selectField(['development','testing','staging','production']) },
			{ key: 'sequence', label: 'Sequence', type: 'number' }, { key: 'protection_level', label: 'Protection Level', ...selectField(['Permissive','Test','Production-like','Restricted']) },
			{ key: 'is_production', label: 'Production', ...checkField }, { key: 'status', label: 'Status', ...selectField(activeStatusOptions) },
		],
		summaryFields: [{ key: 'title', label: 'Title' }, { key: 'deployment_tier', label: 'Tier' }, { key: 'protection_level', label: 'Protection' }, { key: 'status', label: 'Status' }],
		detailFields: [{ key: 'name', label: 'Environment' }, { key: 'code', label: 'Code' }, { key: 'sequence', label: 'Sequence' }, { key: 'is_production', label: 'Production' }], relations: [], actions: [],
	},
	{
		key: 'landscapes', scope: 'platform', label: 'Landscapes', doctype: 'Landscape', route: '/platform/landscapes',
		detailRoute: (name) => `/platform/landscapes/${encodeURIComponent(name)}`, icon: Layers3, creatable: true, editable: true,
		listHelp: 'Versioned Single through Four Tier environment topologies.',
		lifecycleFields: [
			{ key: 'title', label: 'Title', required: true }, { key: 'tier_count', label: 'Tier Count', type: 'number', required: true }, { key: 'version', label: 'Version', type: 'number', default: 1, required: true }, { key: 'status', label: 'Status', default: 'Draft', ...selectField(['Draft','Active','Retired']) },
			{ key: 'environments', label: 'Environments', type: 'table', description: 'Order the environments and assign controls plus independent placement groups.', columns: [
				{ key: 'environment', label: 'Environment', required: true, ...linkField('Environment', ['title']) }, { key: 'site_control_profile', label: 'Site Control Profile', required: true, ...linkField('Site Control Profile', ['title']) }, { key: 'sequence', label: 'Sequence', type: 'number', required: true }, { key: 'bench_group', label: 'Bench Group', required: true }, { key: 'database_group', label: 'Database Group', required: true },
			] },
		],
		summaryFields: [{ key: 'title', label: 'Title' }, { key: 'tier_count', label: 'Tiers', type: 'number' }, { key: 'version', label: 'Version', type: 'number' }, { key: 'status', label: 'Status' }],
		detailFields: [{ key: 'name', label: 'Landscape' }, { key: 'title', label: 'Title' }, { key: 'tier_count', label: 'Tier Count' }, { key: 'version', label: 'Version' }, { key: 'status', label: 'Status' }, { key: 'environments', label: 'Environment policy rows' }], relations: [], actions: [],
	},
	{
		key: 'site-control-profiles', scope: 'platform', label: 'Site Control Profiles', doctype: 'Site Control Profile', route: '/platform/site-control-profiles',
		detailRoute: (name) => `/platform/site-control-profiles/${encodeURIComponent(name)}`, icon: Settings2, creatable: true, editable: true, submittable: true,
		listHelp: 'Versioned environment controls and Bench Test/LATP promotion gates.',
		lifecycleFields: [
			{ key: 'title', label: 'Title', required: true }, { key: 'environment', label: 'Environment', required: true, ...linkField('Environment', ['title']) }, { key: 'profile_code', label: 'Profile Code', required: true }, { key: 'version', label: 'Version', type: 'number', default: 1, required: true }, { key: 'status', label: 'Status', default: 'Draft', ...selectField(['Draft','Active','Retired','Deprecated']) }, { key: 'is_default', label: 'Default for Environment', ...checkField }, { key: 'protection_level', label: 'Protection Level', required: true, ...selectField(['Permissive','Test','Production-like','Restricted']) },
			{ key: 'enable_developer_mode', label: 'Enable Developer Mode', ...checkField }, { key: 'allow_client_scripts', label: 'Allow Client Scripts', ...checkField }, { key: 'allow_server_scripts', label: 'Allow Server Scripts', ...checkField }, { key: 'cors_policy', label: 'CORS Policy', default: 'Disabled', ...selectField(['Disabled','Allowlist']) }, { key: 'cors_origins', label: 'CORS Origins', type: 'textarea' },
			{ key: 'enable_bench_test', label: 'Enable Bench Test', ...checkField }, { key: 'require_bench_test', label: 'Require Bench Test Gate', ...checkField }, { key: 'enable_latp', label: 'Enable LATP', ...checkField }, { key: 'require_latp', label: 'Require LATP Gate', ...checkField }, { key: 'latp_mode', label: 'LATP Mode', default: 'Non-destructive', ...selectField(['Non-destructive','Full']) },
			{ key: 'settings', label: 'Allowlisted Site Settings', type: 'table', description: 'Secret-like keys are rejected server-side.', columns: [{ key: 'setting_key', label: 'Setting Key', required: true }, { key: 'target', label: 'Target', default: 'Site Config', ...selectField(['Site Config','Common Site Config']) }, { key: 'value_type', label: 'Value Type', default: 'String', ...selectField(['String','Integer','Float','Boolean','JSON']) }, { key: 'value', label: 'Value', required: true, type: 'textarea' }] },
		],
		summaryFields: [{ key: 'title', label: 'Title' }, { key: 'environment', label: 'Environment' }, { key: 'profile_code', label: 'Profile Code' }, { key: 'version', label: 'Version', type: 'number' }, { key: 'status', label: 'Status' }],
		detailFields: [{ key: 'name', label: 'Profile' }, { key: 'title', label: 'Title' }, { key: 'environment', label: 'Environment' }, { key: 'profile_code', label: 'Profile Code' }, { key: 'version', label: 'Version' }, { key: 'status', label: 'Status' }, { key: 'is_default', label: 'Default' }, { key: 'protection_level', label: 'Protection Level' }, { key: 'enable_developer_mode', label: 'Developer Mode' }, { key: 'allow_client_scripts', label: 'Client Scripts' }, { key: 'allow_server_scripts', label: 'Server Scripts' }, { key: 'cors_policy', label: 'CORS Policy' }, { key: 'cors_origins', label: 'CORS Origins' }, { key: 'enable_bench_test', label: 'Bench Test' }, { key: 'require_bench_test', label: 'Require Bench Test' }, { key: 'enable_latp', label: 'LATP' }, { key: 'require_latp', label: 'Require LATP' }, { key: 'latp_mode', label: 'LATP Mode' }, { key: 'settings', label: 'Site settings' }], relations: [], actions: [],
	},
	{
		key: 'privacy', scope: 'platform', label: 'Privacy', doctype: 'Privacy', route: '/platform/privacy',
		detailRoute: (name) => `/platform/privacy/${encodeURIComponent(name)}`, icon: ShieldAlert, creatable: true, editable: true,
		listHelp: 'First-class privacy families such as Public, Private Shared, and Private.',
		lifecycleFields: [
			{ key: 'title', label: 'Title', required: true },
		],
		summaryFields: [{ key: 'title', label: 'Title' }],
		detailFields: [{ key: 'name', label: 'Privacy' }, { key: 'title', label: 'Title' }],
		relations: [], actions: [],
	},
	{
		key: 'privacy-profiles', scope: 'platform', label: 'Privacy Profiles', doctype: 'Privacy Profile', route: '/platform/privacy-profiles',
		detailRoute: (name) => `/platform/privacy-profiles/${encodeURIComponent(name)}`, icon: ShieldAlert, creatable: true, editable: true, submittable: true,
		listHelp: 'Submitted Bench and Database isolation policies by Privacy and Environment.',
		lifecycleFields: [
			{ key: 'title', label: 'Title' }, { key: 'privacy', label: 'Privacy', required: true, ...linkField('Privacy', ['title']) }, { key: 'is_default', label: 'Default', ...checkField }, { key: 'customer_summary', label: 'Customer-facing Isolation Summary', type: 'textarea' },
			{ key: 'environment_rules', label: 'Environment Rules', type: 'table', description: 'Bench and Database isolation are configured independently for each Environment.', columns: [
				{ key: 'environment', label: 'Environment', required: true, ...linkField('Environment', ['title']) }, { key: 'bench_boundary', label: 'Bench Boundary', required: true, ...selectField(['Platform','Customer','Subscription','Environment','Site']) }, { key: 'bench_group', label: 'Bench Group', required: true }, { key: 'database_boundary', label: 'Database Boundary', required: true, ...selectField(['Platform','Customer','Subscription','Environment','Bench']) }, { key: 'database_group', label: 'Database Group', required: true },
			] },
		],
		summaryFields: [{ key: 'name', label: 'Profile' }, { key: 'privacy', label: 'Privacy' }, { key: 'is_default', label: 'Default' }],
		detailFields: [{ key: 'name', label: 'Privacy Profile' }, { key: 'title', label: 'Title' }, { key: 'privacy', label: 'Privacy' }, { key: 'is_default', label: 'Default' }, { key: 'customer_summary', label: 'Customer summary' }, { key: 'environment_rules', label: 'Environment isolation rules' }], relations: [], actions: [],
	},
	{
		key: 'environment-test-runs', scope: 'platform', label: 'Environment Test Runs', doctype: 'Environment Test Run', route: '/platform/environment-test-runs',
		detailRoute: (name) => `/platform/environment-test-runs/${encodeURIComponent(name)}`, icon: ScrollText,
		listHelp: 'Bench Test and LATP evidence tied to release and policy versions.',
		summaryFields: [{ key: 'subscription', label: 'Subscription' }, { key: 'environment', label: 'Environment' }, { key: 'test_type', label: 'Test' }, { key: 'status', label: 'Status' }],
		detailFields: [{ key: 'name', label: 'Run' }, { key: 'release', label: 'Release' }, { key: 'execution_mode', label: 'Mode' }, { key: 'policy_hash', label: 'Policy version' }, { key: 'evidence', label: 'Evidence' }], relations: [], actions: [],
	},
	{
		key: 'orchestration-logs',
		scope: 'platform',
		label: 'Orchestration Logs',
		doctype: 'Orchestration Action Log',
		route: '/platform/orchestration-logs',
		detailRoute: (name) => `/platform/orchestration-logs/${encodeURIComponent(name)}`,
		icon: ScrollText,
		listHelp: 'Operator dry-run, reconcile, site request, and DNS action evidence generated by LensCloud control-plane workflows.',
		listLimit: 100,
		summaryFields: [
			{ key: 'action_type', label: 'Action type' },
			{ key: 'status', label: 'Status' },
			{ key: 'bench', label: 'Bench', linkPrefix: '/platform/benches/', ...linkField('Bench') },
			{ key: 'site', label: 'Site', linkPrefix: '/platform/sites/', ...linkField('Site') },
			{ key: 'database_server', label: 'Database Server', linkPrefix: '/platform/database-servers/', ...linkField('Database Server', ['title']) },
			{ key: 'cluster', label: 'Cluster', linkPrefix: '/platform/clusters/', ...linkField('Cluster', ['title', 'cluster_name']) },
			{ key: 'creation', label: 'Created' },
		],
		detailFields: [
			{ key: 'name', label: 'Log ID' },
			{ key: 'action_type', label: 'Action type' },
			{ key: 'status', label: 'Status' },
			{ key: 'dry_run', label: 'Dry run' },
			{ key: 'database_server', label: 'Database Server', linkPrefix: '/platform/database-servers/', ...linkField('Database Server', ['title']) },
			{ key: 'bench', label: 'Bench', linkPrefix: '/platform/benches/', ...linkField('Bench') },
			{ key: 'site', label: 'Site', linkPrefix: '/platform/sites/', ...linkField('Site') },
			{ key: 'release', label: 'Release', linkPrefix: '/platform/releases/', ...linkField('Release', ['image_tag', 'release_group']) },
			{ key: 'region', label: 'Region', linkPrefix: '/platform/regions/', ...linkField('Region') },
			{ key: 'cluster', label: 'Cluster', linkPrefix: '/platform/clusters/', ...linkField('Cluster', ['title', 'cluster_name']) },
			{ key: 'operator_namespace', label: 'Operator namespace' },
			{ key: 'operator_resource_name', label: 'Operator resource name' },
			{ key: 'message', label: 'Message' },
			{ key: 'error', label: 'Error' },
			{ key: 'manifest', label: 'Manifest' },
		],
		actions: [],
	},


	{
		key: 'tools', scope: 'platform', label: 'Tools', doctype: 'Tool', route: '/platform/tools',
		detailRoute: (name) => `/platform/tools/${encodeURIComponent(name)}`, icon: Settings2, creatable: true, editable: true,
		listHelp: 'Reusable platform tools that can be bundled into customer-facing Capabilities.',
		lifecycleFields: [{ key: 'title', label: 'Title', required: true }, { key: 'status', label: 'Status', ...selectField(['Active', 'Inactive', 'Retired']) }, { key: 'description', label: 'Description', type: 'textarea' }],
		summaryFields: [{ key: 'title', label: 'Tool' }, { key: 'status', label: 'Status' }],
		detailFields: [{ key: 'name', label: 'Tool ID' }, { key: 'title', label: 'Title' }, { key: 'status', label: 'Status', ...selectField(['Active', 'Inactive', 'Retired']) }, { key: 'description', label: 'Description' }],
		actions: [],
	},
	{
		key: 'skills', scope: 'platform', label: 'Skills', doctype: 'Skill', route: '/platform/skills',
		detailRoute: (name) => `/platform/skills/${encodeURIComponent(name)}`, icon: CircleHelp, creatable: true, editable: true,
		listHelp: 'Reusable service or automation skills that can be bundled into customer-facing Capabilities.',
		lifecycleFields: [{ key: 'title', label: 'Title', required: true }, { key: 'status', label: 'Status', ...selectField(['Active', 'Inactive', 'Retired']) }, { key: 'description', label: 'Description', type: 'textarea' }],
		summaryFields: [{ key: 'title', label: 'Skill' }, { key: 'status', label: 'Status' }],
		detailFields: [{ key: 'name', label: 'Skill ID' }, { key: 'title', label: 'Title' }, { key: 'status', label: 'Status', ...selectField(['Active', 'Inactive', 'Retired']) }, { key: 'description', label: 'Description' }],
		actions: [],
	},
	{
		key: 'capabilities', scope: 'platform', label: 'Capabilities', doctype: 'Capability', route: '/platform/capabilities',
		detailRoute: (name) => `/platform/capabilities/${encodeURIComponent(name)}`, icon: Sparkles, creatable: true, editable: true,
		listHelp: 'Customer-facing capabilities that bundle apps, tools, skills, and fulfillment policy.',
		lifecycleFields: [
			{ key: 'capability_name', label: 'Capability Name', required: true },
			{ key: 'capability_code', label: 'Capability Code', required: true },
			{ key: 'status', label: 'Status', ...selectField(['Available', 'Planning', 'Beta', 'Coming Soon', 'Retired']) },
			{ key: 'enabled', label: 'Enabled', ...checkField },
		],
		summaryFields: [
			{ key: 'capability_name', label: 'Capability' },
			{ key: 'capability_code', label: 'Code' },
			{ key: 'status', label: 'Status' },
			{ key: 'enabled', label: 'Enabled' },
		],
		detailFields: [
			{ key: 'name', label: 'Capability ID' },
			{ key: 'capability_name', label: 'Capability Name' },
			{ key: 'capability_code', label: 'Capability Code' },
			{ key: 'status', label: 'Status', ...selectField(['Available', 'Planning', 'Beta', 'Coming Soon', 'Retired']) },
			{ key: 'enabled', label: 'Enabled', ...checkField },
			{ key: 'publish_in_customer_portal', label: 'Publish in Customer Portal', ...checkField },
			{ key: 'allow_self_service', label: 'Allow Self Service', ...checkField },
			{ key: 'request_access_only', label: 'Request Access Only', ...checkField },
			{ key: 'short_description', label: 'Short Description' },
			{ key: 'category', label: 'Category', ...linkField('Category', ['category_name']) },
			{ key: 'pricing_model', label: 'Pricing Model', ...linkField('Pricing Model', ['pricing_model_name']) },
			{ key: 'apps', label: 'Apps' },
			{ key: 'tools', label: 'Tools' },
			{ key: 'skills', label: 'Skills' },
		],
		actions: [],
	},
	{
		key: 'subscription-capabilities', scope: 'platform', label: 'Subscription Capabilities', doctype: 'Subscription Capability', route: '/platform/subscription-capabilities',
		detailRoute: (name) => `/platform/subscription-capabilities/${encodeURIComponent(name)}`, icon: Sparkles, creatable: true, editable: true,
		listHelp: 'Durable customer subscription capability entitlement and fulfillment state.',
		summaryFields: [
			{ key: 'customer', label: 'Customer', linkPrefix: '/platform/customers/', ...linkField('Customer', ['first_name', 'last_name']) },
			{ key: 'subscription', label: 'Subscription', linkPrefix: '/platform/subscriptions/', ...linkField('Subscription', ['customer', 'plan', 'status']) },
			{ key: 'capability', label: 'Capability', linkPrefix: '/platform/capabilities/', ...linkField('Capability', ['capability_name']) },
			{ key: 'status', label: 'Status' },
		],
		detailFields: [
			{ key: 'name', label: 'Subscription Capability' },
			{ key: 'customer', label: 'Customer', linkPrefix: '/platform/customers/', ...linkField('Customer', ['first_name', 'last_name']) },
			{ key: 'subscription', label: 'Subscription', linkPrefix: '/platform/subscriptions/', ...linkField('Subscription', ['customer', 'plan', 'status']) },
			{ key: 'capability', label: 'Capability', linkPrefix: '/platform/capabilities/', ...linkField('Capability', ['capability_name']) },
			{ key: 'status', label: 'Status', ...selectField(['Requested', 'Pending Approval', 'Approved', 'Provisioning', 'Active', 'Failed', 'Suspended', 'Cancelled']) },
			{ key: 'landscape', label: 'Landscape', linkPrefix: '/platform/landscapes/', ...linkField('Landscape') },
			{ key: 'environment', label: 'Environment', linkPrefix: '/platform/environments/', ...linkField('Environment') },
			{ key: 'policy', label: 'Policy', linkPrefix: '/platform/capability-landscape-policies/', ...linkField('Capability Landscape Policy', ['capability', 'landscape', 'environment']) },
			{ key: 'last_action_log', label: 'Last Action Log', linkPrefix: '/platform/orchestration-logs/', ...linkField('Orchestration Action Log') },
			{ key: 'last_error', label: 'Last Error', readOnly: true },
		],
		actions: [],
	},
	{
		key: 'capability-landscape-policies', scope: 'platform', label: 'Capability Landscape Policies', doctype: 'Capability Landscape Policy', route: '/platform/capability-landscape-policies',
		detailRoute: (name) => `/platform/capability-landscape-policies/${encodeURIComponent(name)}`, icon: Layers3, creatable: true, editable: true,
		listHelp: 'Landscape and environment progression policy for capability fulfillment.',
		summaryFields: [
			{ key: 'capability', label: 'Capability', linkPrefix: '/platform/capabilities/', ...linkField('Capability', ['capability_name']) },
			{ key: 'landscape', label: 'Landscape', linkPrefix: '/platform/landscapes/', ...linkField('Landscape') },
			{ key: 'environment', label: 'Environment', linkPrefix: '/platform/environments/', ...linkField('Environment') },
			{ key: 'progression_policy', label: 'Policy' },
		],
		detailFields: [
			{ key: 'name', label: 'Policy ID' },
			{ key: 'capability', label: 'Capability', linkPrefix: '/platform/capabilities/', ...linkField('Capability', ['capability_name']) },
			{ key: 'landscape', label: 'Landscape', linkPrefix: '/platform/landscapes/', ...linkField('Landscape') },
			{ key: 'environment', label: 'Environment', linkPrefix: '/platform/environments/', ...linkField('Environment') },
			{ key: 'status', label: 'Status', ...selectField(['Draft', 'Active', 'Paused', 'Retired']) },
			{ key: 'progression_policy', label: 'Progression Policy', ...selectField(['Manual', 'Self Service', 'Approval Required', 'Platform Managed']) },
			{ key: 'fulfillment_timing', label: 'Fulfillment Timing', ...selectField(['At Site Creation', 'After Subscription Approval', 'Manual Action', 'After Bench Upgrade']) },
			{ key: 'approval_required', label: 'Approval Required', ...checkField },
			{ key: 'notes', label: 'Notes' },
		],
		actions: [],
	},

]

export const platformSettings = {
	key: 'settings',
	scope: 'platform',
	label: 'Platform Settings',
	doctype: 'Platform Settings',
	route: '/platform/settings',
	detailRoute: () => '/platform/settings',
	icon: Settings2,
	editable: true,
	singleton: true,
	singletonName: 'Platform Settings',
	listHelp: 'Global LensCloud settings rendered from the Platform Settings DocType metadata.',
	summaryFields: [
		{ key: 'default_plan', label: 'Default plan', ...linkField('Plan', ['title', 'plan_code']) },
		{ key: 'operator_namespace', label: 'Operator namespace' },
		{ key: 'default_storage_class', label: 'Default storage class' },
		{ key: 'root_domain', label: 'Root domain' },
		{ key: 'domain_strategy', label: 'Domain strategy' },
		{ key: 'wildcard_dns_status', label: 'Wildcard DNS' },
		{ key: 'wildcard_tls_status', label: 'Wildcard TLS' },
		{ key: 'ingress_status', label: 'Ingress' },
		{ key: 'billing_integration_status', label: 'Billing status' },
		{ key: 'crm_integration_status', label: 'CRM status' },
		{ key: 'support_integration_status', label: 'Support status' },
	],
	detailFields: [
		{ key: 'default_plan', label: 'Default plan', ...linkField('Plan', ['title', 'plan_code']) },
		{ key: 'operator_namespace', label: 'Operator namespace' },
		{ key: 'default_storage_class', label: 'Default storage class' },
		{ key: 'default_bench_namespace_pattern', label: 'Default bench namespace pattern' },
		{ key: 'root_domain', label: 'Root domain' },
		{ key: 'domain_strategy', label: 'Domain strategy', ...selectField(['Wildcard', 'Custom Domains']) },
		{ key: 'wildcard_dns_status', label: 'Wildcard DNS status', readOnly: true, ...selectField(edgeStatusOptions) },
		{ key: 'wildcard_tls_status', label: 'Wildcard TLS status', readOnly: true, ...selectField(edgeStatusOptions) },
		{ key: 'ingress_status', label: 'Ingress status', readOnly: true, ...selectField(edgeStatusOptions) },
		{ key: 'kubernetes_apply_enabled', label: 'Kubernetes apply enabled', type: 'check' },
		{ key: 'billing_system', label: 'Billing system' },
		{ key: 'billing_integration_enabled', label: 'Billing integration enabled', type: 'check' },
		{ key: 'billing_integration_status', label: 'Billing integration status', ...selectField(integrationStatusOptions) },
		{ key: 'crm_system', label: 'CRM system' },
		{ key: 'crm_integration_enabled', label: 'CRM integration enabled', type: 'check' },
		{ key: 'crm_integration_status', label: 'CRM integration status', ...selectField(integrationStatusOptions) },
		{ key: 'support_system', label: 'Support system' },
		{ key: 'support_integration_enabled', label: 'Support integration enabled', type: 'check' },
		{ key: 'support_integration_status', label: 'Support integration status', ...selectField(integrationStatusOptions) },
	],
}

export const customerResources = [
	{
		key: 'customer-account',
		scope: 'customer',
		label: 'Account',
		doctype: 'Customer',
		route: '/customer/account',
		icon: UserRound,
		listHelp: 'Your customer identity, region, and external account links.',
		summaryFields: [
			{ key: 'first_name', label: 'First name' },
			{ key: 'last_name', label: 'Last name' },
			{ key: 'region', label: 'Primary region', linkPrefix: '/platform/regions/', ...linkField('Region') },
		],
		detailFields: [
			{ key: 'name', label: 'Customer ID' },
			{ key: 'first_name', label: 'First name' },
			{ key: 'last_name', label: 'Last name' },
			{ key: 'region', label: 'Primary region', linkPrefix: '/platform/regions/', ...linkField('Region') },
			{ key: 'external_customer_id', label: 'External ID' },
		],
		associated: true,
		actions: [
			{
				key: 'request-site',
				label: 'Request site',
				icon: SquareArrowOutUpRight,
				description: 'This entry point collects the request in the UI. Backend creation support is not yet wired.',
				backendSupported: false,
				fields: [
					{ key: 'company_name', label: 'Company name', type: 'text', placeholder: 'Acme Incorporated' },
					{ key: 'preferred_region', label: 'Preferred region', placeholder: 'us-east', ...linkField('Region') },
					{ key: 'preferred_release_group', label: 'Preferred release group', placeholder: '2026.06', ...linkField('Release Group') },
					{ key: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Describe the request and rollout constraints.' },
				],
			},
		],
	},
	{
			key: 'customer-sites',
		scope: 'customer',
		label: 'Sites',
		doctype: 'Site',
		route: '/customer/sites',
		detailRoute: (name) => `/customer/sites/${encodeURIComponent(name)}`,
		icon: Globe2,
		listHelp: 'Sites linked to your customer record.',
		customerScoped: true,
		summaryFields: [
			{ key: 'title', label: 'Title' },
			{ key: 'domain', label: 'Domain' },
			{ key: 'site_status', label: 'Site status', ...selectField(siteStatusOptions) },
			{ key: 'provisioning_status', label: 'Provisioning', ...selectField(provisioningStatusOptions) },
			{ key: 'bench', label: 'Bench', linkPrefix: '/platform/benches/', ...linkField('Bench') },
		],
		detailFields: [
			{ key: 'name', label: 'Site ID' },
			{ key: 'title', label: 'Title' },
			{ key: 'domain', label: 'Domain' },
			{ key: 'site_status', label: 'Site status', ...selectField(siteStatusOptions) },
			{ key: 'provisioning_status', label: 'Provisioning status', ...selectField(provisioningStatusOptions) },
			{ key: 'hostname_reservation_status', label: 'Hostname reservation', ...selectField(hostnameStatusOptions) },
			{ key: 'route_status', label: 'Access route', ...selectField(routeStatusOptions) },
			{ key: 'tls_status', label: 'TLS', ...selectField(tlsStatusOptions) },
			{ key: 'access_url', label: 'Access URL' },
			{ key: 'backup_state', label: 'Backup state', ...selectField(backupStateOptions) },
			{ key: 'restore_state', label: 'Restore state', ...selectField(restoreStateOptions) },
			{ key: 'upgrade_state', label: 'Upgrade state', ...selectField(upgradeStateOptions) },
			{ key: 'site_capability_state', label: 'Site Capability State', readOnly: true },
		],
		actions: [
			{
				key: 'request-site',
				label: 'Request site',
				icon: SquareArrowOutUpRight,
				description: 'Create requests are captured in the UI first while backend orchestration remains pending.',
				backendSupported: false,
				fields: [
					{ key: 'company_name', label: 'Company name', type: 'text', placeholder: 'Acme Incorporated' },
					{ key: 'preferred_region', label: 'Preferred region', placeholder: 'us-east', ...linkField('Region') },
					{ key: 'preferred_release_group', label: 'Preferred release group', placeholder: '2026.06', ...linkField('Release Group') },
					{ key: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Describe the request and rollout constraints.' },
				],
			},
		],
	},
]

export const platformNav = [
	{ heading: 'Home', collapsible: false, items: [
		{ key: 'platform-dashboard', label: 'Dashboard', route: '/platform/dashboard', icon: LayoutDashboard },
	] },
	{ heading: 'Customers and Commerce', collapsible: true, items: [
		{ key: 'platform-customers', label: 'Customers', route: '/platform/customers', icon: Users },
		{ key: 'platform-customer-members', label: 'Customer Members', route: '/platform/customer-members', icon: UserRound },
		{ key: 'platform-plans', label: 'Plans', route: '/platform/plans', icon: Package },
		{ key: 'platform-subscriptions', label: 'Subscriptions', route: '/platform/subscriptions', icon: Users },
		{ key: 'platform-capability', label: 'Capability', route: '/platform/capability', icon: Store },
		{ key: 'platform-capability-opted', label: 'Capability Opted', route: '/platform/capability-opted', icon: ListChecks },
	] },
	{ heading: 'Product and Delivery', collapsible: true, keep_closed: true, items: [
		{ key: 'platform-landscapes', label: 'Landscapes', route: '/platform/landscapes', icon: Layers3 },
		{ key: 'platform-environments', label: 'Environments', route: '/platform/environments', icon: Layers3 },
		{ key: 'platform-site-control-profiles', label: 'Site Control Profiles', route: '/platform/site-control-profiles', icon: Settings2 },
		{ key: 'platform-privacy', label: 'Privacy', route: '/platform/privacy', icon: ShieldAlert },
		{ key: 'platform-privacy-profiles', label: 'Privacy Profiles', route: '/platform/privacy-profiles', icon: ShieldAlert },
		{ key: 'platform-release-groups', label: 'Release Groups', route: '/platform/release-groups', icon: Layers3 },
		{ key: 'platform-releases', label: 'Releases', route: '/platform/releases', icon: GitBranch },
		{ key: 'platform-apps', label: 'Apps', route: '/platform/apps', icon: Package },
		{ key: 'platform-tools', label: 'Tools', route: '/platform/tools', icon: Settings2 },
		{ key: 'platform-skills', label: 'Skills', route: '/platform/skills', icon: CircleHelp },
		{ key: 'platform-capabilities', label: 'Capabilities', route: '/platform/capabilities', icon: Sparkles },
		{ key: 'platform-subscription-capabilities', label: 'Subscription Capabilities', route: '/platform/subscription-capabilities', icon: Sparkles },
		{ key: 'platform-capability-landscape-policies', label: 'Capability Policies', route: '/platform/capability-landscape-policies', icon: Layers3 },
	] },
	{ heading: 'Runtime', collapsible: true, keep_closed: true, items: [
		{ key: 'platform-clusters', label: 'Clusters', route: '/platform/clusters', icon: Server },
		{ key: 'platform-runtime-namespaces', label: 'Runtime Namespaces', route: '/platform/runtime-namespaces', icon: Server },
		{ key: 'platform-database-servers', label: 'Database Servers', route: '/platform/database-servers', icon: Database },
		{ key: 'platform-benches', label: 'Benches', route: '/platform/benches', icon: Server },
		{ key: 'platform-sites', label: 'Sites', route: '/platform/sites', icon: Globe2 },
	] },
	{ heading: 'Operations', collapsible: true, keep_closed: true, items: [
		{ key: 'platform-environment-test-runs', label: 'Test Runs', route: '/platform/environment-test-runs', icon: ScrollText },
		{ key: 'platform-orchestration-logs', label: 'Orchestration Logs', route: '/platform/orchestration-logs', icon: ScrollText },
	] },
	{ heading: 'Configuration', collapsible: true, keep_closed: true, items: [
		{ key: 'platform-regions', label: 'Regions', route: '/platform/regions', icon: Globe2 },
		{ key: 'platform-settings', label: 'Platform Settings', route: '/platform/settings', icon: Settings2 },
	] },
]

export const customerNav = [
	{
		heading: 'Customer portal',
		items: [
			{ key: 'customer-dashboard', label: 'Dashboard', note: 'Site status and next steps', route: '/customer/dashboard', icon: LayoutDashboard },
			{ key: 'customer-plans', label: 'Plans', note: 'Choose a subscription', route: '/customer/plans', icon: Package, doctype: 'Plan' },
			{ key: 'customer-subscriptions', label: 'Subscriptions', note: 'Service status', route: '/customer/subscriptions', icon: CreditCard, doctype: 'Subscription' },
			{ key: 'customer-marketplace', label: 'Marketplace', note: 'Capabilities', route: '/customer/marketplace', icon: Sparkles, doctype: 'Capability' },
			{ key: 'customer-members', label: 'Members', note: 'Team access', route: '/customer/members', icon: UserRound, doctype: 'Customer Member' },
		],
	},
	{
		heading: 'Account',
		placement: 'bottom',
		items: [
			{ key: 'customer-account', label: 'Account', note: 'Identity and access', route: '/customer/account', icon: UserRound },
		],
	},
]

export function getResourceByKey(key) {
	return [...platformResources, platformSettings, ...customerResources].find((resource) => resource.key === key) || null
}

export function getResourceByDoctype(doctype) {
	return [...platformResources, platformSettings, ...customerResources].find((resource) => resource.doctype === doctype) || null
}

export function getRoutesForScope(scope) {
	return scope === 'customer' ? customerNav : platformNav
}

export function getHomeRoute(session) {
	if (session?.canAccessPlatform) {
		return '/platform/dashboard'
	}

	return '/customer/dashboard'
}
