import {
	ArrowRight,
	CloudDownload,
	Database,
	Globe2,
	LayoutDashboard,
	Layers3,
	Package,
	GitBranch,
	RefreshCcw,
	Server,
	Settings2,
	Pause,
	ShieldAlert,
	SquareArrowOutUpRight,
	Users,
	UserRound,
	AlertTriangle,
	CircleHelp,
	ScrollText,
} from 'lucide-vue-next'

const linkField = (options, labelFields = ['title']) => ({ type: 'link', options, labelFields })
const selectField = (options) => ({ type: 'select', options })
const checkField = { type: 'check' }

const activeStatusOptions = ['Active', 'Inactive']
const releasePolicyOptions = ['Manual', 'Quality First', 'Production Eligible', 'LTS']
const buildStatusOptions = ['Draft', 'Queued', 'Running', 'Succeeded', 'Failed', 'Cancelled']
const releaseStatusOptions = ['Draft', 'Built', 'Quality', 'Production Eligible', 'Blocked', 'Retired']
const rolloutEligibilityOptions = ['Not Eligible', 'Quality Only', 'Production Eligible', 'Blocked']
const clusterProviderOptions = ['Hcloud', 'AWS', 'Local', 'Other']
const clusterEnvironmentOptions = ['Development', 'Staging', 'Production']
const clusterStatusOptions = ['Draft', 'Active', 'Maintenance', 'Disabled', 'Retired']
const healthStatusOptions = ['Unknown', 'Healthy', 'Degraded', 'Failed']
const benchStatusOptions = ['Draft', 'Pending', 'Accepted', 'Provisioning', 'Ready', 'Upgrading', 'Suspended', 'Deleting', 'Failed', 'Retired', 'Unknown']
const upgradePolicyOptions = ['Manual', 'Scheduled', 'Auto Quality', 'Auto Production Eligible']
const upgradeSopStatusOptions = ['Draft', 'Scheduled', 'Precheck', 'Ready', 'Running', 'Verifying', 'Completed', 'Rolled Back', 'Failed']
const siteStatusOptions = ['Draft', 'Requested', 'Accepted', 'Provisioning', 'Ready', 'Active', 'Suspended', 'Deleting', 'Failed', 'Deleted', 'Unknown']
const provisioningStatusOptions = ['Not Started', 'Pending', 'Accepted', 'Running', 'Ready', 'Failed', 'Unknown']
const backupStateOptions = ['Not Configured', 'Scheduled', 'Running', 'Succeeded', 'Failed']
const restoreStateOptions = ['Not Requested', 'Pending', 'Running', 'Succeeded', 'Failed']
const upgradeStateOptions = ['Not Scheduled', 'Scheduled', 'Running', 'Verifying', 'Succeeded', 'Failed']
const regionDeploymentOptions = ['Not Deployable', 'Active', 'Maintenance', 'Disabled']
const planStatusOptions = ['Active', 'Inactive', 'Retired']
const benchPolicyOptions = ['Shared Bench', 'Dedicated Bench', 'Manual Placement']
const integrationStatusOptions = ['Not Configured', 'Configured', 'Healthy', 'Degraded', 'Disabled']
const databaseStatusOptions = ['Draft', 'Pending', 'Provisioning', 'Ready', 'Maintenance', 'Failed', 'Unknown']
const databaseProvisioningOptions = ['Not Started', 'Pending', 'Accepted', 'Running', 'Ready', 'Failed', 'Unknown']
const databaseProvisioningTypeOptions = ['Operator Managed', 'External']
const routeStatusOptions = ['Not Checked', 'Pending', 'Ready', 'Failed', 'Unknown']
const tlsStatusOptions = ['Inherited', 'Ready', 'Failed', 'Unknown']
const hostnameStatusOptions = ['Pending', 'Reserved', 'Conflict', 'Released']
const edgeStatusOptions = ['Unknown', 'Ready', 'Degraded', 'Failed']

export const platformResources = [
	{
		key: 'customers',
		scope: 'platform',
		label: 'Customers',
		doctype: 'Customer',
		route: '/platform/customers',
		detailRoute: (name) => `/platform/customers/${encodeURIComponent(name)}`,
		icon: Users,
		listHelp: 'Customer records, identity links, and primary region placement.',
		summaryFields: [
			{ key: 'first_name', label: 'First name' },
			{ key: 'last_name', label: 'Last name' },
			{ key: 'region', label: 'Primary region', linkPrefix: '/platform/regions/', ...linkField('Region') },
			{ key: 'external_customer_id', label: 'External ID' },
		],
		detailFields: [
			{ key: 'name', label: 'Customer ID' },
			{ key: 'first_name', label: 'First name' },
			{ key: 'last_name', label: 'Last name' },
			{ key: 'user', label: 'User' },
			{ key: 'region', label: 'Primary region', linkPrefix: '/platform/regions/', ...linkField('Region') },
			{ key: 'external_customer_id', label: 'External ID' },
		],
		relations: [
			{
				label: 'Sites',
				doctype: 'Site',
				linkField: 'customer',
				sourceField: 'name',
				fields: ['name', 'title', 'bench', 'modified'],
				route: (name) => `/platform/sites/${encodeURIComponent(name)}`,
			},
		],
		actions: [
			{
				key: 'request-site',
				label: 'Request site',
				icon: SquareArrowOutUpRight,
				description: 'Capture a new site request in the UI. Backend creation support is not wired yet.',
				backendSupported: false,
				fields: [
					{ key: 'company_name', label: 'Company name', type: 'text', placeholder: 'Acme Incorporated' },
					{ key: 'preferred_region', label: 'Preferred region', placeholder: 'us-east', ...linkField('Region') },
					{ key: 'preferred_release_group', label: 'Preferred release group', placeholder: '2026.06', ...linkField('Release Group') },
					{ key: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Describe the request and rollout constraints.' },
				],
			},
		],
	},
	{
		key: 'release-groups',
		scope: 'platform',
		label: 'Release Groups',
		doctype: 'Release Group',
		route: '/platform/release-groups',
		detailRoute: (name) => `/platform/release-groups/${encodeURIComponent(name)}`,
		icon: Layers3,
		listHelp: 'Release group is master data for a product/image family. Deployable versions live in Release.',
		creatable: true,
		editable: true,
		lifecycleFields: [
			{ key: 'title', label: 'Title', required: true },
			{ key: 'status', label: 'Status', default: 'Active', ...selectField(activeStatusOptions) },
			{ key: 'registry_url', label: 'Registry URL' },
			{ key: 'image_repository', label: 'Image repository' },
			{ key: 'supported_frappe_major_version', label: 'Supported Frappe major' },
			{ key: 'release_policy', label: 'Release policy', default: 'Manual', ...selectField(releasePolicyOptions) },
			{ key: 'apps_metadata', label: 'Apps metadata', type: 'textarea' },
		],
		summaryFields: [
			{ key: 'title', label: 'Title' },
			{ key: 'status', label: 'Status', ...selectField(activeStatusOptions) },
			{ key: 'registry_url', label: 'Registry URL' },
			{ key: 'image_repository', label: 'Image repository' },
		],
		detailFields: [
			{ key: 'name', label: 'Release group ID' },
			{ key: 'title', label: 'Title' },
			{ key: 'status', label: 'Status', ...selectField(activeStatusOptions) },
			{ key: 'registry_url', label: 'Registry URL' },
			{ key: 'image_repository', label: 'Image repository' },
			{ key: 'included_apps', label: 'Included apps' },
			{ key: 'apps_metadata', label: 'Apps metadata' },
			{ key: 'supported_frappe_major_version', label: 'Supported Frappe major' },
			{ key: 'release_policy', label: 'Release policy', ...selectField(releasePolicyOptions) },
		],
		relations: [
			{
				label: 'Releases',
				doctype: 'Release',
				linkField: 'release_group',
				sourceField: 'name',
				fields: ['name', 'image_tag', 'release_status', 'rollout_eligibility'],
				route: (name) => `/platform/releases/${encodeURIComponent(name)}`,
			},
			{
				label: 'Bench adoption by release group',
				doctype: 'Bench',
				linkField: 'release_group',
				sourceField: 'name',
				fields: ['name', 'title', 'current_release', 'next_release', 'bench_status'],
				route: (name) => `/platform/benches/${encodeURIComponent(name)}`,
			},
		],
		actions: [
			{
				key: 'create-release',
				label: 'Create release',
				icon: ArrowRight,
				description: 'Release creation is a platform workflow. Backend pipeline creation remains a gap until wired.',
				backendSupported: false,
				fields: [
					{ key: 'image_tag', label: 'Image tag', type: 'text', placeholder: 'v2026.06.1' },
					{ key: 'pipeline_reference', label: 'Pipeline reference', type: 'text', placeholder: 'CI build URL or ID' },
					{ key: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Release intent and compatibility notes.' },
				],
			},
		],
	},
	{
		key: 'apps',
		scope: 'platform',
		label: 'Apps',
		doctype: 'App',
		route: '/platform/apps',
		detailRoute: (name) => `/platform/apps/${encodeURIComponent(name)}`,
		icon: Package,
		listHelp: 'Application master data used by Release Groups through the Included Apps table multiselect.',
		creatable: true,
		editable: true,
		lifecycleFields: [
			{ key: 'title', label: 'Title', required: true },
			{ key: 'repository_url', label: 'Repository URL' },
		],
		summaryFields: [
			{ key: 'title', label: 'Title' },
			{ key: 'repository_url', label: 'Repository URL' },
		],
		detailFields: [
			{ key: 'name', label: 'App ID' },
			{ key: 'title', label: 'Title' },
			{ key: 'repository_url', label: 'Repository URL' },
		],
		relations: [],
		actions: [],
	},
	{
		key: 'releases',
		scope: 'platform',
		label: 'Releases',
		doctype: 'Release',
		route: '/platform/releases',
		detailRoute: (name) => `/platform/releases/${encodeURIComponent(name)}`,
		icon: GitBranch,
		listHelp: 'Release is the transactional deployable image/version inside a Release Group.',
		creatable: true,
		editable: true,
		submittable: true,
		lifecycleFields: [
			{ key: 'release_group', label: 'Release group', required: true, ...linkField('Release Group') },
			{ key: 'image_tag', label: 'Image tag', required: true },
			{ key: 'image_digest', label: 'Image digest' },
			{ key: 'build_status', label: 'Build status', default: 'Draft', ...selectField(buildStatusOptions) },
			{ key: 'build_pipeline_reference', label: 'Build/pipeline reference' },
			{ key: 'release_status', label: 'Release status', default: 'Draft', ...selectField(releaseStatusOptions) },
			{ key: 'rollout_eligibility', label: 'Rollout eligibility', default: 'Not Eligible', ...selectField(rolloutEligibilityOptions) },
			{ key: 'build_date', label: 'Build date', type: 'datetime' },
			{ key: 'promoted_date', label: 'Promoted date', type: 'datetime' },
			{ key: 'release_notes', label: 'Changelog / release notes', type: 'textarea' },
			{ key: 'compatibility_notes', label: 'Compatibility notes', type: 'textarea' },
		],
		summaryFields: [
			{ key: 'release_group', label: 'Release group', linkPrefix: '/platform/release-groups/', ...linkField('Release Group') },
			{ key: 'image_tag', label: 'Image tag' },
			{ key: 'build_status', label: 'Build status', ...selectField(buildStatusOptions) },
			{ key: 'release_status', label: 'Release status', ...selectField(releaseStatusOptions) },
			{ key: 'rollout_eligibility', label: 'Rollout eligibility', ...selectField(rolloutEligibilityOptions) },
			{ key: 'docstatus', label: 'Docstatus' },
		],
		detailFields: [
			{ key: 'name', label: 'Release ID' },
			{ key: 'release_group', label: 'Release group', linkPrefix: '/platform/release-groups/', ...linkField('Release Group') },
			{ key: 'image_tag', label: 'Image tag' },
			{ key: 'image_digest', label: 'Image digest' },
			{ key: 'build_status', label: 'Build status', ...selectField(buildStatusOptions) },
			{ key: 'build_pipeline_reference', label: 'Build/pipeline reference' },
			{ key: 'release_status', label: 'Release status', ...selectField(releaseStatusOptions) },
			{ key: 'build_date', label: 'Build date', type: 'datetime' },
			{ key: 'promoted_date', label: 'Promoted date', type: 'datetime' },
			{ key: 'release_notes', label: 'Changelog / release notes' },
			{ key: 'compatibility_notes', label: 'Compatibility notes' },
			{ key: 'rollout_eligibility', label: 'Rollout eligibility', ...selectField(rolloutEligibilityOptions) },
		],
		relations: [
			{
				label: 'Current benches',
				doctype: 'Bench',
				linkField: 'current_release',
				sourceField: 'name',
				fields: ['name', 'release_group', 'bench_status'],
				route: (name) => `/platform/benches/${encodeURIComponent(name)}`,
			},
			{
				label: 'Next-release benches',
				doctype: 'Bench',
				linkField: 'next_release',
				sourceField: 'name',
				fields: ['name', 'release_group', 'upgrade_sop_status'],
				route: (name) => `/platform/benches/${encodeURIComponent(name)}`,
			},
		],
		actions: [
			{
				key: 'promote-release',
				label: 'Promote release',
				icon: ArrowRight,
				description: 'Promotion is exposed as a UI entry point. Pipeline/operator execution remains a backend gap.',
				backendSupported: false,
				fields: [
					{ key: 'target_status', label: 'Target status', placeholder: 'Quality or Production Eligible', ...selectField(releaseStatusOptions) },
					{ key: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Promotion notes and expected impact.' },
				],
			},
		],
	},
	{
		key: 'clusters',
		scope: 'platform',
		label: 'Clusters',
		doctype: 'Cluster',
		route: '/platform/clusters',
		detailRoute: (name) => `/platform/clusters/${encodeURIComponent(name)}`,
		icon: Server,
		listHelp: 'Registered runtime targets. Regions choose the active Cluster used for Bench and Site placement.',
		creatable: true,
		editable: true,
		lifecycleFields: [
			{ key: 'title', label: 'Title', required: true },
			{ key: 'cluster_name', label: 'Cluster name', required: true },
			{ key: 'region', label: 'Region', ...linkField('Region') },
			{ key: 'provider', label: 'Provider', default: 'Hcloud', ...selectField(clusterProviderOptions) },
			{ key: 'environment', label: 'Environment', default: 'Development', ...selectField(clusterEnvironmentOptions) },
			{ key: 'status', label: 'Status', default: 'Active', ...selectField(clusterStatusOptions) },
			{ key: 'manager_host', label: 'Manager host' },
			{ key: 'headlamp_url', label: 'Headlamp URL' },
			{ key: 'operator_namespace', label: 'Operator namespace', default: 'frappe-operator-system' },
			{ key: 'default_storage_class', label: 'Default storage class', default: 'local-path' },
			{ key: 'default_bench_namespace_pattern', label: 'Default bench namespace pattern', default: 'bench-{bench}' },
			{ key: 'kubeconfig_reference', label: 'Kubeconfig reference' },
			{ key: 'credential_reference', label: 'Credential reference' },
			{ key: 'domain_strategy', label: 'Domain strategy', default: 'Wildcard', ...selectField(['Wildcard', 'Custom Domains']) },
			{ key: 'ingress_class', label: 'Ingress class', default: 'traefik' },
			{ key: 'wildcard_hostname', label: 'Wildcard hostname' },
		],
		summaryFields: [
			{ key: 'cluster_name', label: 'Cluster name' },
			{ key: 'region', label: 'Region', linkPrefix: '/platform/regions/', ...linkField('Region') },
			{ key: 'provider', label: 'Provider', ...selectField(clusterProviderOptions) },
			{ key: 'status', label: 'Status', ...selectField(clusterStatusOptions) },
			{ key: 'health_status', label: 'Health', ...selectField(healthStatusOptions) },
		],
		detailFields: [
			{ key: 'name', label: 'Cluster ID' },
			{ key: 'cluster_name', label: 'Cluster name' },
			{ key: 'region', label: 'Region', linkPrefix: '/platform/regions/', ...linkField('Region') },
			{ key: 'provider', label: 'Provider', ...selectField(clusterProviderOptions) },
			{ key: 'environment', label: 'Environment', ...selectField(clusterEnvironmentOptions) },
			{ key: 'status', label: 'Status', ...selectField(clusterStatusOptions) },
			{ key: 'manager_host', label: 'Manager host' },
			{ key: 'manager_public_ip', label: 'Manager public IP' },
			{ key: 'manager_private_ip', label: 'Manager private IP' },
			{ key: 'headlamp_url', label: 'Headlamp URL' },
			{ key: 'access_method', label: 'Access method' },
			{ key: 'operator_namespace', label: 'Operator namespace' },
			{ key: 'default_runtime_namespace', label: 'Default runtime namespace' },
			{ key: 'default_storage_class', label: 'Default storage class' },
			{ key: 'default_bench_namespace_pattern', label: 'Default bench namespace pattern' },
			{ key: 'kubeconfig_reference', label: 'Kubeconfig reference' },
			{ key: 'credential_reference', label: 'Credential reference' },
			{ key: 'domain_strategy', label: 'Domain strategy', ...selectField(['Wildcard', 'Custom Domains']) },
			{ key: 'wildcard_hostname', label: 'Wildcard hostname' },
			{ key: 'wildcard_dns_status', label: 'Wildcard DNS', readOnly: true, ...selectField(edgeStatusOptions) },
			{ key: 'wildcard_tls_status', label: 'Wildcard TLS', readOnly: true, ...selectField(edgeStatusOptions) },
			{ key: 'ingress_status', label: 'Ingress', readOnly: true, ...selectField(edgeStatusOptions) },
			{ key: 'ingress_class', label: 'Ingress class' },
			{ key: 'health_status', label: 'Health status', ...selectField(healthStatusOptions) },
			{ key: 'last_sync_time', label: 'Last sync' },
			{ key: 'last_error', label: 'Last error' },
		],
		relations: [
			{ label: 'Regions', doctype: 'Region', linkField: 'cluster', sourceField: 'name', fields: ['name', 'title', 'deployment_status'], route: (name) => `/platform/regions/${encodeURIComponent(name)}` },
			{ label: 'Benches', doctype: 'Bench', linkField: 'cluster', sourceField: 'name', fields: ['name', 'title', 'bench_status'], route: (name) => `/platform/benches/${encodeURIComponent(name)}` },
			{ label: 'Sites', doctype: 'Site', linkField: 'cluster', sourceField: 'name', fields: ['name', 'title', 'site_status', 'dns_status'], route: (name) => `/platform/sites/${encodeURIComponent(name)}` },
		],
		actions: [],
	},
	{
		key: 'database-servers',
		scope: 'platform',
		label: 'Database Servers',
		doctype: 'Database Server',
		route: '/platform/database-servers',
		detailRoute: (name) => `/platform/database-servers/${encodeURIComponent(name)}`,
		icon: Database,
		listHelp: 'MariaDB runtime capacity with Region, privacy, ownership, readiness, and Bench attachment policy.',
		creatable: true,
		editable: true,
		lifecycleFields: [
			{ key: 'title', label: 'Title', required: true },
			{ key: 'database_engine', label: 'Database engine', default: 'MariaDB', ...selectField(['MariaDB']) },
			{ key: 'provisioning_type', label: 'Provisioning type', default: 'Operator Managed', ...selectField(databaseProvisioningTypeOptions) },
			{ key: 'region', label: 'Region', required: true, ...linkField('Region') },
			{ key: 'privacy', label: 'Privacy', required: true, ...linkField('Privacy') },
			{ key: 'owner_customer', label: 'Owner Customer', ...linkField('Customer', ['first_name', 'last_name']) },
			{ key: 'privacy_boundary', label: 'Privacy boundary' },
			{ key: 'kubernetes_namespace', label: 'Kubernetes namespace', default: 'default' },
			{ key: 'operator_resource_name', label: 'MariaDB resource name', required: true },
			{ key: 'image', label: 'MariaDB image', default: 'mariadb:10.11' },
			{ key: 'storage_class', label: 'Storage class', default: 'local-path' },
			{ key: 'storage_size', label: 'Storage size', default: '8Gi' },
			{ key: 'replica_count', label: 'Replica count', default: 1, type: 'number' },
			{ key: 'root_credential_secret_reference', label: 'Root Secret reference' },
			{ key: 'maximum_bench_count', label: 'Maximum Bench count', default: 0, type: 'number' },
		],
		summaryFields: [
			{ key: 'region', label: 'Region', linkPrefix: '/platform/regions/', ...linkField('Region') },
			{ key: 'privacy', label: 'Privacy', ...linkField('Privacy') },
			{ key: 'database_status', label: 'Database status', ...selectField(databaseStatusOptions) },
			{ key: 'health_status', label: 'Health', ...selectField(healthStatusOptions) },
			{ key: 'attached_bench_count', label: 'Benches' },
		],
		detailFields: [
			{ key: 'name', label: 'Database Server ID' },
			{ key: 'title', label: 'Title' },
			{ key: 'database_engine', label: 'Database engine', ...selectField(['MariaDB']) },
			{ key: 'provisioning_type', label: 'Provisioning type', ...selectField(databaseProvisioningTypeOptions) },
			{ key: 'region', label: 'Region', linkPrefix: '/platform/regions/', ...linkField('Region') },
			{ key: 'cluster', label: 'Cluster', readOnly: true, linkPrefix: '/platform/clusters/', ...linkField('Cluster') },
			{ key: 'privacy', label: 'Privacy', ...linkField('Privacy') },
			{ key: 'owner_customer', label: 'Owner Customer', linkPrefix: '/platform/customers/', ...linkField('Customer', ['first_name', 'last_name']) },
			{ key: 'privacy_boundary', label: 'Privacy boundary' },
			{ key: 'kubernetes_namespace', label: 'Kubernetes namespace' },
			{ key: 'operator_resource_name', label: 'MariaDB resource name' },
			{ key: 'image', label: 'MariaDB image' },
			{ key: 'storage_class', label: 'Storage class' },
			{ key: 'storage_size', label: 'Storage size' },
			{ key: 'replica_count', label: 'Replica count', type: 'number' },
			{ key: 'root_credential_secret_reference', label: 'Root Secret reference' },
			{ key: 'maximum_bench_count', label: 'Maximum Bench count', type: 'number' },
			{ key: 'attached_bench_count', label: 'Attached Benches', readOnly: true },
			{ key: 'database_status', label: 'Database status', readOnly: true, ...selectField(databaseStatusOptions) },
			{ key: 'provisioning_status', label: 'Provisioning status', readOnly: true, ...selectField(databaseProvisioningOptions) },
			{ key: 'health_status', label: 'Health status', readOnly: true, ...selectField(healthStatusOptions) },
			{ key: 'last_sync_time', label: 'Last sync', readOnly: true },
			{ key: 'last_error', label: 'Last error', readOnly: true },
		],
		relations: [
			{ label: 'Benches', doctype: 'Bench', linkField: 'database_server', sourceField: 'name', fields: ['name', 'title', 'owner_customer', 'privacy', 'bench_status'], route: (name) => `/platform/benches/${encodeURIComponent(name)}` },
		],
		actions: [
			{ key: 'dry-run-database-server', label: 'Preview MariaDB manifest', icon: SquareArrowOutUpRight, description: 'Generate a secret-safe MariaDB Operator manifest.', backendSupported: true, method: 'lenscloud.api.orchestration.dry_run_database_server_manifest', paramsFromRecord: { database_server: 'name' }, fields: [] },
			{ key: 'reconcile-database-server', label: 'Reconcile Database Server', icon: RefreshCcw, description: 'Idempotently apply when restricted Kubernetes access and apply are enabled; otherwise returns a dry-run.', backendSupported: true, method: 'lenscloud.api.orchestration.reconcile_database_server', paramsFromRecord: { database_server: 'name' }, fields: [{ key: 'dry_run', label: 'Dry run', ...checkField }] },
			{ key: 'sync-database-server', label: 'Sync runtime status', icon: RefreshCcw, description: 'Read MariaDB runtime readiness from Kubernetes.', backendSupported: true, method: 'lenscloud.api.orchestration.sync_database_server_status', paramsFromRecord: { database_server: 'name' }, fields: [] },
		],
	},
	{
		key: 'benches',
		scope: 'platform',
		label: 'Benches',
		doctype: 'Bench',
		route: '/platform/benches',
		detailRoute: (name) => `/platform/benches/${encodeURIComponent(name)}`,
		icon: Server,
		listHelp: 'Bench records group runtime capacity by Release Group, current Release, next Release, and operator target.',
		creatable: true,
		editable: true,
		lifecycleFields: [
			{ key: 'title', label: 'Title', required: true },
			{ key: 'release_group', label: 'Release group', required: true, ...linkField('Release Group') },
			{ key: 'current_release', label: 'Current Release', required: true, ...linkField('Release', ['image_tag', 'release_group']) },
			{ key: 'next_release', label: 'Next Release', ...linkField('Release', ['image_tag', 'release_group']) },
			{ key: 'region', label: 'Region', required: true, ...linkField('Region') },
			{ key: 'privacy', label: 'Privacy', ...linkField('Privacy') },
			{ key: 'owner_customer', label: 'Owner Customer', ...linkField('Customer', ['first_name', 'last_name']) },
			{ key: 'privacy_boundary', label: 'Privacy boundary' },
			{ key: 'database_server', label: 'Database Server', required: true, ...linkField('Database Server', ['title', 'privacy', 'region']) },
			{ key: 'kubernetes_namespace', label: 'Kubernetes namespace' },
			{ key: 'operator_resource_name', label: 'Operator resource name' },
			{ key: 'storage_class', label: 'Storage class' },
			{ key: 'bench_status', label: 'Bench status', default: 'Draft', ...selectField(benchStatusOptions) },
			{ key: 'upgrade_window', label: 'Upgrade schedule/window' },
			{ key: 'upgrade_policy', label: 'Upgrade policy', default: 'Manual', ...selectField(upgradePolicyOptions) },
		],
		summaryFields: [
			{ key: 'title', label: 'Title' },
			{ key: 'release_group', label: 'Release group', linkPrefix: '/platform/release-groups/', ...linkField('Release Group') },
			{ key: 'cluster', label: 'Cluster', linkPrefix: '/platform/clusters/', ...linkField('Cluster', ['title', 'cluster_name']) },
			{ key: 'current_release', label: 'Current release', linkPrefix: '/platform/releases/', ...linkField('Release', ['image_tag', 'release_group']) },
			{ key: 'next_release', label: 'Next release', linkPrefix: '/platform/releases/', ...linkField('Release', ['image_tag', 'release_group']) },
			{ key: 'bench_status', label: 'Bench status', ...selectField(benchStatusOptions) },
		],
		detailFields: [
			{ key: 'name', label: 'Bench ID' },
			{ key: 'title', label: 'Title' },
			{ key: 'release_group', label: 'Release group', linkPrefix: '/platform/release-groups/', ...linkField('Release Group') },
			{ key: 'current_release', label: 'Current release', linkPrefix: '/platform/releases/', ...linkField('Release', ['image_tag', 'release_group']) },
			{ key: 'next_release', label: 'Next release', linkPrefix: '/platform/releases/', ...linkField('Release', ['image_tag', 'release_group']) },
			{ key: 'region', label: 'Region', linkPrefix: '/platform/regions/', ...linkField('Region') },
			{ key: 'cluster', label: 'Cluster', linkPrefix: '/platform/clusters/', ...linkField('Cluster', ['title', 'cluster_name']) },
			{ key: 'privacy', label: 'Privacy', ...linkField('Privacy') },
			{ key: 'owner_customer', label: 'Owner Customer', linkPrefix: '/platform/customers/', ...linkField('Customer', ['first_name', 'last_name']) },
			{ key: 'privacy_boundary', label: 'Privacy boundary' },
			{ key: 'database_server', label: 'Database Server', linkPrefix: '/platform/database-servers/', ...linkField('Database Server', ['title', 'privacy', 'region']) },
			{ key: 'cluster_runtime_target', label: 'Cluster/runtime target' },
			{ key: 'kubernetes_namespace', label: 'Kubernetes namespace' },
			{ key: 'operator_resource_name', label: 'Operator resource name' },
			{ key: 'storage_class', label: 'Storage class' },
			{ key: 'bench_status', label: 'Bench status', ...selectField(benchStatusOptions) },
			{ key: 'upgrade_window', label: 'Upgrade schedule/window' },
			{ key: 'upgrade_policy', label: 'Upgrade policy', ...selectField(upgradePolicyOptions) },
			{ key: 'upgrade_sop_status', label: 'Upgrade/SOP status', ...selectField(upgradeSopStatusOptions) },
		],
		relations: [
			{
				label: 'Sites',
				doctype: 'Site',
				field: 'bench',
				fields: ['name', 'title', 'customer', 'modified'],
				route: (name) => `/platform/sites/${encodeURIComponent(name)}`,
			},
		],
		actions: [
			{
				key: 'dry-run-bench',
				label: 'Dry-run FrappeBench',
				icon: SquareArrowOutUpRight,
				description: 'Generate the operator FrappeBench manifest from Region-derived Cluster, Release, and Bench fields. No Kubernetes apply is performed.',
				backendSupported: true,
				method: 'lenscloud.api.orchestration.dry_run_bench_manifest',
				paramsFromRecord: { bench: 'name' },
				fields: [],
			},
			{
				key: 'reconcile-bench-dry-run',
				label: 'Reconcile bench dry-run',
				icon: RefreshCcw,
				description: 'Run the safe Bench reconcile path. Kubernetes apply remains disabled unless backend credentials and settings are later wired.',
				backendSupported: true,
				method: 'lenscloud.api.orchestration.reconcile_bench',
				paramsFromRecord: { bench: 'name' },
				fields: [{ key: 'dry_run', label: 'Dry run', ...checkField }],
			},
			{ key: 'sync-bench', label: 'Sync runtime status', icon: RefreshCcw, description: 'Read FrappeBench status from the selected Cluster.', backendSupported: true, method: 'lenscloud.api.orchestration.sync_bench_status', paramsFromRecord: { bench: 'name' }, fields: [] },
			{
				key: 'upgrade-bench',
				label: 'Upgrade bench',
				icon: RefreshCcw,
				description: 'Upgrade controls are surfaced in the UI, while the orchestration backend remains a gap.',
				backendSupported: false,
				fields: [
					{ key: 'target_release', label: 'Target Release', placeholder: 'Release document name', ...linkField('Release', ['image_tag', 'release_group']) },
					{ key: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Why this upgrade is needed.' },
				],
			},
			{
				key: 'retire-bench',
				label: 'Retire bench',
				icon: ShieldAlert,
				description: 'Retirement is represented in the UI; backend execution is not wired yet.',
				backendSupported: false,
				fields: [
					{ key: 'reason', label: 'Reason', type: 'textarea', placeholder: 'Explain the retirement request.' },
				],
			},
		],
	},
	{
		key: 'sites',
		scope: 'platform',
		label: 'Sites',
		doctype: 'Site',
		route: '/platform/sites',
		detailRoute: (name) => `/platform/sites/${encodeURIComponent(name)}`,
		icon: Globe2,
		listHelp: 'Tenant instances inside benches, tied to customers and runtime placement.',
		creatable: true,
		editable: true,
		lifecycleFields: [
			{ key: 'customer', label: 'Customer', ...linkField('Customer', ['first_name', 'last_name']) },
			{ key: 'bench', label: 'Bench', required: true, ...linkField('Bench') },
			{ key: 'region', label: 'Region', required: true, ...linkField('Region') },
			{ key: 'plan', label: 'Plan', ...linkField('Plan', ['title', 'plan_code']) },
			{ key: 'subdomain', label: 'Subdomain', required: true },
			{ key: 'site_status', label: 'Site status', default: 'Draft', ...selectField(siteStatusOptions) },
			{ key: 'provisioning_status', label: 'Provisioning status', default: 'Not Started', ...selectField(provisioningStatusOptions) },
			{ key: 'operator_resource_name', label: 'Operator resource name' },
			{ key: 'hostname_reservation_status', label: 'Hostname reservation', default: 'Pending', ...selectField(hostnameStatusOptions) },
		],
		summaryFields: [
			{ key: 'title', label: 'Title' },
			{ key: 'domain', label: 'Domain' },
			{ key: 'site_status', label: 'Site status', ...selectField(siteStatusOptions) },
			{ key: 'cluster', label: 'Cluster', linkPrefix: '/platform/clusters/', ...linkField('Cluster', ['title', 'cluster_name']) },
			{ key: 'provisioning_status', label: 'Provisioning', ...selectField(provisioningStatusOptions) },
			{ key: 'route_status', label: 'Access route', ...selectField(routeStatusOptions) },
		],
		detailFields: [
			{ key: 'name', label: 'Site ID' },
			{ key: 'title', label: 'Title', readOnly: true },
			{ key: 'customer', label: 'Customer', linkPrefix: '/platform/customers/', ...linkField('Customer', ['first_name', 'last_name']) },
			{ key: 'bench', label: 'Bench', linkPrefix: '/platform/benches/', ...linkField('Bench') },
			{ key: 'region', label: 'Region', linkPrefix: '/platform/regions/', ...linkField('Region') },
			{ key: 'cluster', label: 'Cluster', linkPrefix: '/platform/clusters/', ...linkField('Cluster', ['title', 'cluster_name']) },
			{ key: 'plan', label: 'Plan', linkPrefix: '/platform/plans/', ...linkField('Plan', ['title', 'plan_code']) },
			{ key: 'subdomain', label: 'Subdomain' },
			{ key: 'domain', label: 'Domain', readOnly: true },
			{ key: 'site_status', label: 'Site status', ...selectField(siteStatusOptions) },
			{ key: 'provisioning_status', label: 'Provisioning status', ...selectField(provisioningStatusOptions) },
			{ key: 'operator_resource_name', label: 'Operator resource name' },
			{ key: 'hostname_reservation_status', label: 'Hostname reservation', readOnly: true, ...selectField(hostnameStatusOptions) },
			{ key: 'route_status', label: 'Route status', readOnly: true, ...selectField(routeStatusOptions) },
			{ key: 'tls_status', label: 'TLS status', readOnly: true, ...selectField(tlsStatusOptions) },
			{ key: 'access_url', label: 'Access URL', readOnly: true },
			{ key: 'last_route_check', label: 'Last route check', readOnly: true },
			{ key: 'route_error', label: 'Route error', readOnly: true },
			{ key: 'backup_state', label: 'Backup state', ...selectField(backupStateOptions) },
			{ key: 'restore_state', label: 'Restore state', ...selectField(restoreStateOptions) },
			{ key: 'upgrade_state', label: 'Upgrade state', ...selectField(upgradeStateOptions) },
		],
		relations: [
			{
				label: 'Bench',
				doctype: 'Bench',
				linkField: 'name',
				sourceField: 'bench',
				fields: ['name', 'title', 'release_group', 'region'],
				route: (name) => `/platform/benches/${encodeURIComponent(name)}`,
			},
		],
		actions: [
			{
				key: 'dry-run-site',
				label: 'Dry-run FrappeSite',
				icon: SquareArrowOutUpRight,
				description: 'Generate the operator FrappeSite manifest. No Kubernetes apply is performed.',
				backendSupported: true,
				method: 'lenscloud.api.orchestration.dry_run_site_manifest',
				paramsFromRecord: { site: 'name' },
				fields: [],
			},
			{ key: 'reconcile-site', label: 'Reconcile Site', icon: RefreshCcw, description: 'Idempotently apply the FrappeSite and Traefik wildcard route when restricted access is enabled.', backendSupported: true, method: 'lenscloud.api.orchestration.reconcile_site', paramsFromRecord: { site: 'name' }, fields: [{ key: 'dry_run', label: 'Dry run', ...checkField }] },
			{ key: 'sync-site', label: 'Sync provisioning and access', icon: RefreshCcw, description: 'Read operator status and verify the HTTPS route.', backendSupported: true, method: 'lenscloud.api.orchestration.sync_site_status', paramsFromRecord: { site: 'name' }, fields: [] },
			{
				key: 'create-site',
				label: 'Create site',
				icon: SquareArrowOutUpRight,
				description: 'Site creation is shown as a UI flow while the backend contract is still pending.',
				backendSupported: false,
				fields: [
					{ key: 'company_name', label: 'Company name', type: 'text', placeholder: 'Acme Incorporated' },
					{ key: 'target_region', label: 'Target region', placeholder: 'us-east', ...linkField('Region') },
					{ key: 'target_bench', label: 'Target bench', placeholder: 'bench-us-east-01', ...linkField('Bench') },
					{ key: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Any placement or migration constraints.' },
				],
			},
			{
				key: 'suspend-site',
				label: 'Suspend site',
				icon: Pause,
				description: 'Suspension is surfaced here, but the actual state transition remains a backend gap.',
				backendSupported: false,
				fields: [
					{ key: 'reason', label: 'Reason', type: 'textarea', placeholder: 'Why is the site being suspended?' },
				],
			},
			{
				key: 'delete-site',
				label: 'Delete site',
				icon: AlertTriangle,
				description: 'Destructive deletion is represented in the UI, but backend execution is not wired in this pass.',
				backendSupported: false,
				fields: [
					{ key: 'confirmation', label: 'Confirmation', type: 'text', placeholder: 'Type DELETE to confirm intent' },
					{ key: 'reason', label: 'Reason', type: 'textarea', placeholder: 'Explain the deletion request.' },
				],
			},
			{
				key: 'backup-site',
				label: 'Backup site',
				icon: CloudDownload,
				description: 'Backup request entry point is present in the UI; backend dispatch remains a gap.',
				backendSupported: false,
				fields: [
					{ key: 'label', label: 'Backup label', type: 'text', placeholder: 'nightly-2026-06-01' },
					{ key: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Retention or restore intent.' },
				],
			},
			{
				key: 'restore-site',
				label: 'Restore site',
				icon: Database,
				description: 'Restore entry point exists in the UI; backend execution is not implemented here.',
				backendSupported: false,
				fields: [
					{ key: 'backup_name', label: 'Backup name', type: 'text', placeholder: 'latest backup label' },
					{ key: 'target_time', label: 'Target time', type: 'text', placeholder: 'optional timestamp' },
					{ key: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Restore intent and constraints.' },
				],
			},
			{
				key: 'upgrade-site',
				label: 'Upgrade site',
				icon: RefreshCcw,
				description: 'Upgrade entry point is a UI-only control until the orchestration backend lands.',
				backendSupported: false,
				fields: [
					{ key: 'target_release', label: 'Target Release', placeholder: 'Release document name', ...linkField('Release', ['image_tag', 'release_group']) },
					{ key: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Expected impact and timing.' },
				],
			},
		],
	},
	{
		key: 'regions',
		scope: 'platform',
		label: 'Regions',
		doctype: 'Region',
		route: '/platform/regions',
		detailRoute: (name) => `/platform/regions/${encodeURIComponent(name)}`,
		icon: Globe2,
		listHelp: 'Placement hierarchy for region-aware and environment-aware workflows.',
		tree: {
			parentField: 'parent_region',
			groupField: 'is_group',
			orderBy: 'lft asc',
			extraFields: ['lft', 'rgt'],
		},
		listLimit: 200,
		summaryFields: [
			{ key: 'title', label: 'Title' },
			{ key: 'parent_region', label: 'Parent region', linkPrefix: '/platform/regions/', ...linkField('Region') },
			{ key: 'cluster', label: 'Cluster', linkPrefix: '/platform/clusters/', ...linkField('Cluster', ['title', 'cluster_name']) },
			{ key: 'deployment_status', label: 'Deployment status', ...selectField(regionDeploymentOptions) },
			{ key: 'is_group', label: 'Group', ...checkField },
		],
		detailFields: [
			{ key: 'name', label: 'Region ID' },
			{ key: 'title', label: 'Title' },
			{ key: 'parent_region', label: 'Parent region', linkPrefix: '/platform/regions/', ...linkField('Region') },
			{ key: 'cluster', label: 'Cluster', linkPrefix: '/platform/clusters/', ...linkField('Cluster', ['title', 'cluster_name']) },
			{ key: 'deployment_status', label: 'Deployment status', ...selectField(regionDeploymentOptions) },
			{ key: 'is_group', label: 'Group', ...checkField },
		],
		relations: [
			{
				label: 'Customers',
				doctype: 'Customer',
				linkField: 'region',
				sourceField: 'name',
				fields: ['name', 'first_name', 'last_name', 'external_customer_id'],
				route: (name) => `/platform/customers/${encodeURIComponent(name)}`,
			},
			{
				label: 'Benches',
				doctype: 'Bench',
				linkField: 'region',
				sourceField: 'name',
				fields: ['name', 'title', 'release_group', 'privacy'],
				route: (name) => `/platform/benches/${encodeURIComponent(name)}`,
			},
		],
		actions: [],
	},

	{
		key: 'plans',
		scope: 'platform',
		label: 'Plans',
		doctype: 'Plan',
		route: '/platform/plans',
		detailRoute: (name) => `/platform/plans/${encodeURIComponent(name)}`,
		icon: Package,
		listHelp: 'Commercial plan master data. Free plan enables first customer self-service site requests.',
		creatable: true,
		editable: true,
		lifecycleFields: [
			{ key: 'title', label: 'Title', required: true },
			{ key: 'plan_code', label: 'Plan code', required: true },
			{ key: 'status', label: 'Status', default: 'Active', ...selectField(planStatusOptions) },
			{ key: 'is_default', label: 'Is default', ...checkField },
			{ key: 'is_free', label: 'Is free', ...checkField },
			{ key: 'monthly_price', label: 'Monthly price', default: '0' },
			{ key: 'site_limit', label: 'Site limit', default: '1' },
			{ key: 'bench_policy', label: 'Bench policy', default: 'Shared Bench', ...selectField(benchPolicyOptions) },
			{ key: 'billing_system_reference', label: 'Billing system reference' },
			{ key: 'description', label: 'Description', type: 'textarea' },
		],
		summaryFields: [
			{ key: 'title', label: 'Title' },
			{ key: 'plan_code', label: 'Plan code' },
			{ key: 'status', label: 'Status', ...selectField(planStatusOptions) },
			{ key: 'is_free', label: 'Free' },
			{ key: 'is_default', label: 'Default' },
		],
		detailFields: [
			{ key: 'name', label: 'Plan ID' },
			{ key: 'title', label: 'Title' },
			{ key: 'plan_code', label: 'Plan code' },
			{ key: 'status', label: 'Status', ...selectField(planStatusOptions) },
			{ key: 'is_default', label: 'Is default', ...checkField },
			{ key: 'is_free', label: 'Is free', ...checkField },
			{ key: 'monthly_price', label: 'Monthly price' },
			{ key: 'site_limit', label: 'Site limit' },
			{ key: 'bench_policy', label: 'Bench policy', ...selectField(benchPolicyOptions) },
			{ key: 'billing_system_reference', label: 'Billing system reference' },
			{ key: 'description', label: 'Description' },
		],
		relations: [
			{ label: 'Sites', doctype: 'Site', linkField: 'plan', sourceField: 'name', fields: ['name', 'title', 'domain', 'site_status'], route: (name) => `/platform/sites/${encodeURIComponent(name)}` },
		],
		actions: [],
	},
	{
		key: 'orchestration-logs',
		scope: 'platform',
		label: 'Orchestration Logs',
		doctype: 'Orchestration Action Log',
		route: '/platform/orchestration-logs',
		detailRoute: (name) => `/platform/orchestration-logs/${encodeURIComponent(name)}`,
		icon: ScrollText,
		listHelp: 'Operator dry-run, reconcile, site request, and DNS action evidence generated by LensCloud control-plane workflows.',
		listLimit: 100,
		summaryFields: [
			{ key: 'action_type', label: 'Action type' },
			{ key: 'status', label: 'Status' },
			{ key: 'bench', label: 'Bench', linkPrefix: '/platform/benches/', ...linkField('Bench') },
			{ key: 'site', label: 'Site', linkPrefix: '/platform/sites/', ...linkField('Site') },
			{ key: 'database_server', label: 'Database Server', linkPrefix: '/platform/database-servers/', ...linkField('Database Server', ['title']) },
			{ key: 'cluster', label: 'Cluster', linkPrefix: '/platform/clusters/', ...linkField('Cluster', ['title', 'cluster_name']) },
			{ key: 'creation', label: 'Created' },
		],
		detailFields: [
			{ key: 'name', label: 'Log ID' },
			{ key: 'action_type', label: 'Action type' },
			{ key: 'status', label: 'Status' },
			{ key: 'dry_run', label: 'Dry run' },
			{ key: 'database_server', label: 'Database Server', linkPrefix: '/platform/database-servers/', ...linkField('Database Server', ['title']) },
			{ key: 'bench', label: 'Bench', linkPrefix: '/platform/benches/', ...linkField('Bench') },
			{ key: 'site', label: 'Site', linkPrefix: '/platform/sites/', ...linkField('Site') },
			{ key: 'release', label: 'Release', linkPrefix: '/platform/releases/', ...linkField('Release', ['image_tag', 'release_group']) },
			{ key: 'region', label: 'Region', linkPrefix: '/platform/regions/', ...linkField('Region') },
			{ key: 'cluster', label: 'Cluster', linkPrefix: '/platform/clusters/', ...linkField('Cluster', ['title', 'cluster_name']) },
			{ key: 'operator_namespace', label: 'Operator namespace' },
			{ key: 'operator_resource_name', label: 'Operator resource name' },
			{ key: 'message', label: 'Message' },
			{ key: 'error', label: 'Error' },
			{ key: 'manifest', label: 'Manifest' },
		],
		relations: [],
		actions: [],
	},

]

export const platformSettings = {
	key: 'settings',
	scope: 'platform',
	label: 'Platform Settings',
	doctype: 'Platform Settings',
	route: '/platform/settings',
	icon: Settings2,
	editable: true,
	summaryFields: [
		{ key: 'default_plan', label: 'Default plan', ...linkField('Plan', ['title', 'plan_code']) },
		{ key: 'operator_namespace', label: 'Operator namespace' },
		{ key: 'default_storage_class', label: 'Default storage class' },
		{ key: 'root_domain', label: 'Root domain' },
		{ key: 'domain_strategy', label: 'Domain strategy' },
		{ key: 'wildcard_dns_status', label: 'Wildcard DNS' },
		{ key: 'wildcard_tls_status', label: 'Wildcard TLS' },
		{ key: 'ingress_status', label: 'Ingress' },
		{ key: 'billing_integration_status', label: 'Billing status' },
		{ key: 'crm_integration_status', label: 'CRM status' },
		{ key: 'support_integration_status', label: 'Support status' },
	],
	detailFields: [
		{ key: 'default_plan', label: 'Default plan', ...linkField('Plan', ['title', 'plan_code']) },
		{ key: 'operator_namespace', label: 'Operator namespace' },
		{ key: 'default_storage_class', label: 'Default storage class' },
		{ key: 'default_bench_namespace_pattern', label: 'Default bench namespace pattern' },
		{ key: 'root_domain', label: 'Root domain' },
		{ key: 'domain_strategy', label: 'Domain strategy', ...selectField(['Wildcard', 'Custom Domains']) },
		{ key: 'wildcard_dns_status', label: 'Wildcard DNS status', readOnly: true, ...selectField(edgeStatusOptions) },
		{ key: 'wildcard_tls_status', label: 'Wildcard TLS status', readOnly: true, ...selectField(edgeStatusOptions) },
		{ key: 'ingress_status', label: 'Ingress status', readOnly: true, ...selectField(edgeStatusOptions) },
		{ key: 'kubernetes_apply_enabled', label: 'Kubernetes apply enabled', type: 'check' },
		{ key: 'billing_system', label: 'Billing system' },
		{ key: 'billing_integration_enabled', label: 'Billing integration enabled', type: 'check' },
		{ key: 'billing_integration_status', label: 'Billing integration status', ...selectField(integrationStatusOptions) },
		{ key: 'crm_system', label: 'CRM system' },
		{ key: 'crm_integration_enabled', label: 'CRM integration enabled', type: 'check' },
		{ key: 'crm_integration_status', label: 'CRM integration status', ...selectField(integrationStatusOptions) },
		{ key: 'support_system', label: 'Support system' },
		{ key: 'support_integration_enabled', label: 'Support integration enabled', type: 'check' },
		{ key: 'support_integration_status', label: 'Support integration status', ...selectField(integrationStatusOptions) },
	],
}

export const customerResources = [
	{
		key: 'customer-account',
		scope: 'customer',
		label: 'Account',
		doctype: 'Customer',
		route: '/customer/account',
		icon: UserRound,
		listHelp: 'Your customer identity, region, and external account links.',
		summaryFields: [
			{ key: 'first_name', label: 'First name' },
			{ key: 'last_name', label: 'Last name' },
			{ key: 'region', label: 'Primary region', linkPrefix: '/platform/regions/', ...linkField('Region') },
		],
		detailFields: [
			{ key: 'name', label: 'Customer ID' },
			{ key: 'first_name', label: 'First name' },
			{ key: 'last_name', label: 'Last name' },
			{ key: 'region', label: 'Primary region', linkPrefix: '/platform/regions/', ...linkField('Region') },
			{ key: 'external_customer_id', label: 'External ID' },
		],
		associated: true,
		actions: [
			{
				key: 'request-site',
				label: 'Request site',
				icon: SquareArrowOutUpRight,
				description: 'This entry point collects the request in the UI. Backend creation support is not yet wired.',
				backendSupported: false,
				fields: [
					{ key: 'company_name', label: 'Company name', type: 'text', placeholder: 'Acme Incorporated' },
					{ key: 'preferred_region', label: 'Preferred region', placeholder: 'us-east', ...linkField('Region') },
					{ key: 'preferred_release_group', label: 'Preferred release group', placeholder: '2026.06', ...linkField('Release Group') },
					{ key: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Describe the request and rollout constraints.' },
				],
			},
		],
	},
	{
			key: 'customer-sites',
		scope: 'customer',
		label: 'Sites',
		doctype: 'Site',
		route: '/customer/sites',
		detailRoute: (name) => `/customer/sites/${encodeURIComponent(name)}`,
		icon: Globe2,
		listHelp: 'Sites linked to your customer record.',
		customerScoped: true,
		summaryFields: [
			{ key: 'title', label: 'Title' },
			{ key: 'domain', label: 'Domain' },
			{ key: 'site_status', label: 'Site status', ...selectField(siteStatusOptions) },
			{ key: 'provisioning_status', label: 'Provisioning', ...selectField(provisioningStatusOptions) },
			{ key: 'bench', label: 'Bench', linkPrefix: '/platform/benches/', ...linkField('Bench') },
		],
		detailFields: [
			{ key: 'name', label: 'Site ID' },
			{ key: 'title', label: 'Title' },
			{ key: 'domain', label: 'Domain' },
			{ key: 'site_status', label: 'Site status', ...selectField(siteStatusOptions) },
			{ key: 'provisioning_status', label: 'Provisioning status', ...selectField(provisioningStatusOptions) },
			{ key: 'hostname_reservation_status', label: 'Hostname reservation', ...selectField(hostnameStatusOptions) },
			{ key: 'route_status', label: 'Access route', ...selectField(routeStatusOptions) },
			{ key: 'tls_status', label: 'TLS', ...selectField(tlsStatusOptions) },
			{ key: 'access_url', label: 'Access URL' },
			{ key: 'backup_state', label: 'Backup state', ...selectField(backupStateOptions) },
			{ key: 'restore_state', label: 'Restore state', ...selectField(restoreStateOptions) },
			{ key: 'upgrade_state', label: 'Upgrade state', ...selectField(upgradeStateOptions) },
		],
		relations: [
			{
				label: 'Bench',
				doctype: 'Bench',
				linkField: 'name',
				sourceField: 'bench',
				fields: ['name', 'title', 'release_group', 'region'],
				route: (name) => `/platform/benches/${encodeURIComponent(name)}`,
			},
		],
		actions: [
			{
				key: 'request-site',
				label: 'Request site',
				icon: SquareArrowOutUpRight,
				description: 'Create requests are captured in the UI first while backend orchestration remains pending.',
				backendSupported: false,
				fields: [
					{ key: 'company_name', label: 'Company name', type: 'text', placeholder: 'Acme Incorporated' },
					{ key: 'preferred_region', label: 'Preferred region', placeholder: 'us-east', ...linkField('Region') },
					{ key: 'preferred_release_group', label: 'Preferred release group', placeholder: '2026.06', ...linkField('Release Group') },
					{ key: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Describe the request and rollout constraints.' },
				],
			},
		],
	},
]

export const platformNav = [
	{
		heading: 'Platform console',
		items: [
			{ key: 'platform-dashboard', label: 'Dashboard', note: 'System status and record shortcuts', route: '/platform/dashboard', icon: LayoutDashboard },
			{ key: 'platform-customers', label: 'Customers', note: 'Identity and access', route: '/platform/customers', icon: Users },
			{ key: 'platform-release-groups', label: 'Release Groups', note: 'Image family master data', route: '/platform/release-groups', icon: Layers3 },
			{ key: 'platform-apps', label: 'Apps', note: 'Included app master data', route: '/platform/apps', icon: Package },
			{ key: 'platform-releases', label: 'Releases', note: 'Deployable versions', route: '/platform/releases', icon: GitBranch },
			{ key: 'platform-clusters', label: 'Clusters', note: 'Runtime targets', route: '/platform/clusters', icon: Server },
			{ key: 'platform-database-servers', label: 'Database Servers', note: 'MariaDB capacity and isolation', route: '/platform/database-servers', icon: Database },
			{ key: 'platform-benches', label: 'Benches', note: 'Runtime grouping', route: '/platform/benches', icon: Server },
			{ key: 'platform-sites', label: 'Sites', note: 'Tenant instances', route: '/platform/sites', icon: Globe2 },
			{ key: 'platform-regions', label: 'Regions', note: 'Placement hierarchy', route: '/platform/regions', icon: Globe2 },
			{ key: 'platform-plans', label: 'Plans', note: 'Commercial tiers', route: '/platform/plans', icon: Package },
			{ key: 'platform-orchestration-logs', label: 'Orchestration Logs', note: 'Dry-run and action evidence', route: '/platform/orchestration-logs', icon: ScrollText },
			{ key: 'platform-settings', label: 'Platform Settings', note: 'Wildcard edge and integrations', route: '/platform/settings', icon: Settings2 },
		],
	},
]

export const customerNav = [
	{
		heading: 'Customer portal',
		items: [
			{ key: 'customer-dashboard', label: 'Dashboard', note: 'Site status and next steps', route: '/customer/dashboard', icon: LayoutDashboard },
			{ key: 'customer-sites', label: 'Sites', note: 'Manage tenant instances', route: '/customer/sites', icon: Globe2 },
			{ key: 'customer-create-site', label: 'Create Site', note: 'Start a new site request', route: '/customer/create-site', icon: SquareArrowOutUpRight },
			{ key: 'customer-account', label: 'Account', note: 'Identity and region', route: '/customer/account', icon: UserRound },
		],
	},
]

export function getResourceByKey(key) {
	return [...platformResources, ...customerResources].find((resource) => resource.key === key) || null
}

export function getRoutesForScope(scope) {
	return scope === 'customer' ? customerNav : platformNav
}

export function getHomeRoute(session) {
	if (session?.canAccessPlatform) {
		return '/platform/dashboard'
	}

	return '/customer/dashboard'
}
