import {
	ArrowRight,
	CloudDownload,
	Database,
	Globe2,
	LayoutDashboard,
	Layers3,
	Package,
	GitBranch,
	RefreshCcw,
	Server,
	Settings2,
	Pause,
	ShieldAlert,
	SquareArrowOutUpRight,
	Users,
	UserRound,
	AlertTriangle,
	CircleHelp,
} from 'lucide-vue-next'

export const platformResources = [
	{
		key: 'customers',
		scope: 'platform',
		label: 'Customers',
		doctype: 'Customer',
		route: '/platform/customers',
		detailRoute: (name) => `/platform/customers/${encodeURIComponent(name)}`,
		icon: Users,
		listHelp: 'Customer records, identity links, and primary region placement.',
		summaryFields: [
			{ key: 'first_name', label: 'First name' },
			{ key: 'last_name', label: 'Last name' },
			{ key: 'region', label: 'Primary region', linkPrefix: '/platform/regions/' },
			{ key: 'external_customer_id', label: 'External ID' },
		],
		detailFields: [
			{ key: 'name', label: 'Customer ID' },
			{ key: 'first_name', label: 'First name' },
			{ key: 'last_name', label: 'Last name' },
			{ key: 'user', label: 'User' },
			{ key: 'region', label: 'Primary region', linkPrefix: '/platform/regions/' },
			{ key: 'external_customer_id', label: 'External ID' },
		],
		relations: [
			{
				label: 'Sites',
				doctype: 'Site',
				linkField: 'customer',
				sourceField: 'name',
				fields: ['name', 'title', 'bench', 'modified'],
				route: (name) => `/platform/sites/${encodeURIComponent(name)}`,
			},
		],
		actions: [
			{
				key: 'request-site',
				label: 'Request site',
				icon: SquareArrowOutUpRight,
				description: 'Capture a new site request in the UI. Backend creation support is not wired yet.',
				backendSupported: false,
				fields: [
					{ key: 'company_name', label: 'Company name', type: 'text', placeholder: 'Acme Incorporated' },
					{ key: 'preferred_region', label: 'Preferred region', type: 'text', placeholder: 'us-east' },
					{ key: 'preferred_release_group', label: 'Preferred release group', type: 'text', placeholder: '2026.06' },
					{ key: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Describe the request and rollout constraints.' },
				],
			},
		],
	},
	{
		key: 'release-groups',
		scope: 'platform',
		label: 'Release Groups',
		doctype: 'Release Group',
		route: '/platform/release-groups',
		detailRoute: (name) => `/platform/release-groups/${encodeURIComponent(name)}`,
		icon: Layers3,
		listHelp: 'Release group is master data for a product/image family. Deployable versions live in Release.',
		creatable: true,
		editable: true,
		lifecycleFields: [
			{ key: 'title', label: 'Title', required: true },
			{ key: 'status', label: 'Status', default: 'Active' },
			{ key: 'registry_url', label: 'Registry URL' },
			{ key: 'image_repository', label: 'Image repository' },
			{ key: 'supported_frappe_major_version', label: 'Supported Frappe major' },
			{ key: 'release_policy', label: 'Release policy', default: 'Manual' },
			{ key: 'apps_metadata', label: 'Apps metadata', type: 'textarea' },
		],
		summaryFields: [
			{ key: 'title', label: 'Title' },
			{ key: 'status', label: 'Status' },
			{ key: 'registry_url', label: 'Registry URL' },
			{ key: 'image_repository', label: 'Image repository' },
		],
		detailFields: [
			{ key: 'name', label: 'Release group ID' },
			{ key: 'title', label: 'Title' },
			{ key: 'status', label: 'Status' },
			{ key: 'registry_url', label: 'Registry URL' },
			{ key: 'image_repository', label: 'Image repository' },
			{ key: 'included_apps', label: 'Included apps' },
			{ key: 'apps_metadata', label: 'Apps metadata' },
			{ key: 'supported_frappe_major_version', label: 'Supported Frappe major' },
			{ key: 'release_policy', label: 'Release policy' },
		],
		relations: [
			{
				label: 'Releases',
				doctype: 'Release',
				linkField: 'release_group',
				sourceField: 'name',
				fields: ['name', 'image_tag', 'release_status', 'rollout_eligibility'],
				route: (name) => `/platform/releases/${encodeURIComponent(name)}`,
			},
			{
				label: 'Bench adoption by release group',
				doctype: 'Bench',
				linkField: 'release_group',
				sourceField: 'name',
				fields: ['name', 'title', 'current_release', 'next_release', 'bench_status'],
				route: (name) => `/platform/benches/${encodeURIComponent(name)}`,
			},
		],
		actions: [
			{
				key: 'create-release',
				label: 'Create release',
				icon: ArrowRight,
				description: 'Release creation is a platform workflow. Backend pipeline creation remains a gap until wired.',
				backendSupported: false,
				fields: [
					{ key: 'image_tag', label: 'Image tag', type: 'text', placeholder: 'v2026.06.1' },
					{ key: 'pipeline_reference', label: 'Pipeline reference', type: 'text', placeholder: 'CI build URL or ID' },
					{ key: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Release intent and compatibility notes.' },
				],
			},
		],
	},
	{
		key: 'apps',
		scope: 'platform',
		label: 'Apps',
		doctype: 'App',
		route: '/platform/apps',
		detailRoute: (name) => `/platform/apps/${encodeURIComponent(name)}`,
		icon: Package,
		listHelp: 'Application master data used by Release Groups through the Included Apps table multiselect.',
		creatable: true,
		editable: true,
		lifecycleFields: [
			{ key: 'title', label: 'Title', required: true },
			{ key: 'repository_url', label: 'Repository URL' },
		],
		summaryFields: [
			{ key: 'title', label: 'Title' },
			{ key: 'repository_url', label: 'Repository URL' },
		],
		detailFields: [
			{ key: 'name', label: 'App ID' },
			{ key: 'title', label: 'Title' },
			{ key: 'repository_url', label: 'Repository URL' },
		],
		relations: [],
		actions: [],
	},
	{
		key: 'releases',
		scope: 'platform',
		label: 'Releases',
		doctype: 'Release',
		route: '/platform/releases',
		detailRoute: (name) => `/platform/releases/${encodeURIComponent(name)}`,
		icon: GitBranch,
		listHelp: 'Release is the transactional deployable image/version inside a Release Group.',
		creatable: true,
		editable: true,
		submittable: true,
		lifecycleFields: [
			{ key: 'release_group', label: 'Release group', required: true },
			{ key: 'image_tag', label: 'Image tag', required: true },
			{ key: 'image_digest', label: 'Image digest' },
			{ key: 'build_status', label: 'Build status', default: 'Draft' },
			{ key: 'build_pipeline_reference', label: 'Build/pipeline reference' },
			{ key: 'release_status', label: 'Release status', default: 'Draft' },
			{ key: 'rollout_eligibility', label: 'Rollout eligibility', default: 'Not Eligible' },
			{ key: 'build_date', label: 'Build date' },
			{ key: 'promoted_date', label: 'Promoted date' },
			{ key: 'release_notes', label: 'Changelog / release notes', type: 'textarea' },
			{ key: 'compatibility_notes', label: 'Compatibility notes', type: 'textarea' },
		],
		summaryFields: [
			{ key: 'release_group', label: 'Release group', linkPrefix: '/platform/release-groups/' },
			{ key: 'image_tag', label: 'Image tag' },
			{ key: 'build_status', label: 'Build status' },
			{ key: 'release_status', label: 'Release status' },
			{ key: 'rollout_eligibility', label: 'Rollout eligibility' },
			{ key: 'docstatus', label: 'Docstatus' },
		],
		detailFields: [
			{ key: 'name', label: 'Release ID' },
			{ key: 'release_group', label: 'Release group', linkPrefix: '/platform/release-groups/' },
			{ key: 'image_tag', label: 'Image tag' },
			{ key: 'image_digest', label: 'Image digest' },
			{ key: 'build_status', label: 'Build status' },
			{ key: 'build_pipeline_reference', label: 'Build/pipeline reference' },
			{ key: 'release_status', label: 'Release status' },
			{ key: 'build_date', label: 'Build date' },
			{ key: 'promoted_date', label: 'Promoted date' },
			{ key: 'release_notes', label: 'Changelog / release notes' },
			{ key: 'compatibility_notes', label: 'Compatibility notes' },
			{ key: 'rollout_eligibility', label: 'Rollout eligibility' },
		],
		relations: [
			{
				label: 'Current benches',
				doctype: 'Bench',
				linkField: 'current_release',
				sourceField: 'name',
				fields: ['name', 'release_group', 'bench_status'],
				route: (name) => `/platform/benches/${encodeURIComponent(name)}`,
			},
			{
				label: 'Next-release benches',
				doctype: 'Bench',
				linkField: 'next_release',
				sourceField: 'name',
				fields: ['name', 'release_group', 'upgrade_sop_status'],
				route: (name) => `/platform/benches/${encodeURIComponent(name)}`,
			},
		],
		actions: [
			{
				key: 'promote-release',
				label: 'Promote release',
				icon: ArrowRight,
				description: 'Promotion is exposed as a UI entry point. Pipeline/operator execution remains a backend gap.',
				backendSupported: false,
				fields: [
					{ key: 'target_status', label: 'Target status', type: 'text', placeholder: 'Quality or Production Eligible' },
					{ key: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Promotion notes and expected impact.' },
				],
			},
		],
	},
	{
		key: 'benches',
		scope: 'platform',
		label: 'Benches',
		doctype: 'Bench',
		route: '/platform/benches',
		detailRoute: (name) => `/platform/benches/${encodeURIComponent(name)}`,
		icon: Server,
		listHelp: 'Bench records group runtime capacity by Release Group, current Release, next Release, and operator target.',
		summaryFields: [
			{ key: 'title', label: 'Title' },
			{ key: 'release_group', label: 'Release group', linkPrefix: '/platform/release-groups/' },
			{ key: 'current_release', label: 'Current release', linkPrefix: '/platform/releases/' },
			{ key: 'next_release', label: 'Next release', linkPrefix: '/platform/releases/' },
			{ key: 'bench_status', label: 'Bench status' },
		],
		detailFields: [
			{ key: 'name', label: 'Bench ID' },
			{ key: 'title', label: 'Title' },
			{ key: 'release_group', label: 'Release group', linkPrefix: '/platform/release-groups/' },
			{ key: 'current_release', label: 'Current release', linkPrefix: '/platform/releases/' },
			{ key: 'next_release', label: 'Next release', linkPrefix: '/platform/releases/' },
			{ key: 'region', label: 'Region', linkPrefix: '/platform/regions/' },
			{ key: 'privacy', label: 'Privacy' },
			{ key: 'cluster_runtime_target', label: 'Cluster/runtime target' },
			{ key: 'kubernetes_namespace', label: 'Kubernetes namespace' },
			{ key: 'operator_resource_name', label: 'Operator resource name' },
			{ key: 'storage_class', label: 'Storage class' },
			{ key: 'bench_status', label: 'Bench status' },
			{ key: 'upgrade_window', label: 'Upgrade schedule/window' },
			{ key: 'upgrade_policy', label: 'Upgrade policy' },
			{ key: 'upgrade_sop_status', label: 'Upgrade/SOP status' },
		],
		relations: [
			{
				label: 'Sites',
				doctype: 'Site',
				field: 'bench',
				fields: ['name', 'title', 'customer', 'modified'],
				route: (name) => `/platform/sites/${encodeURIComponent(name)}`,
			},
		],
		actions: [
			{
				key: 'upgrade-bench',
				label: 'Upgrade bench',
				icon: RefreshCcw,
				description: 'Upgrade controls are surfaced in the UI, while the orchestration backend remains a gap.',
				backendSupported: false,
				fields: [
					{ key: 'target_release', label: 'Target Release', type: 'text', placeholder: 'Release document name' },
					{ key: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Why this upgrade is needed.' },
				],
			},
			{
				key: 'retire-bench',
				label: 'Retire bench',
				icon: ShieldAlert,
				description: 'Retirement is represented in the UI; backend execution is not wired yet.',
				backendSupported: false,
				fields: [
					{ key: 'reason', label: 'Reason', type: 'textarea', placeholder: 'Explain the retirement request.' },
				],
			},
		],
	},
	{
		key: 'sites',
		scope: 'platform',
		label: 'Sites',
		doctype: 'Site',
		route: '/platform/sites',
		detailRoute: (name) => `/platform/sites/${encodeURIComponent(name)}`,
		icon: Globe2,
		listHelp: 'Tenant instances inside benches, tied to customers and runtime placement.',
		summaryFields: [
			{ key: 'title', label: 'Title' },
			{ key: 'domain', label: 'Domain' },
			{ key: 'site_status', label: 'Site status' },
			{ key: 'provisioning_status', label: 'Provisioning' },
			{ key: 'bench', label: 'Bench', linkPrefix: '/platform/benches/' },
		],
		detailFields: [
			{ key: 'name', label: 'Site ID' },
			{ key: 'title', label: 'Title' },
			{ key: 'customer', label: 'Customer', linkPrefix: '/platform/customers/' },
			{ key: 'bench', label: 'Bench', linkPrefix: '/platform/benches/' },
			{ key: 'subdomain', label: 'Subdomain' },
			{ key: 'domain', label: 'Domain' },
			{ key: 'site_status', label: 'Site status' },
			{ key: 'provisioning_status', label: 'Provisioning status' },
			{ key: 'operator_resource_name', label: 'Operator resource name' },
			{ key: 'dns_status', label: 'DNS status' },
			{ key: 'backup_state', label: 'Backup state' },
			{ key: 'restore_state', label: 'Restore state' },
			{ key: 'upgrade_state', label: 'Upgrade state' },
		],
		relations: [
			{
				label: 'Bench',
				doctype: 'Bench',
				linkField: 'name',
				sourceField: 'bench',
				fields: ['name', 'title', 'release_group', 'region'],
				route: (name) => `/platform/benches/${encodeURIComponent(name)}`,
			},
		],
		actions: [
			{
				key: 'create-site',
				label: 'Create site',
				icon: SquareArrowOutUpRight,
				description: 'Site creation is shown as a UI flow while the backend contract is still pending.',
				backendSupported: false,
				fields: [
					{ key: 'company_name', label: 'Company name', type: 'text', placeholder: 'Acme Incorporated' },
					{ key: 'target_region', label: 'Target region', type: 'text', placeholder: 'us-east' },
					{ key: 'target_bench', label: 'Target bench', type: 'text', placeholder: 'bench-us-east-01' },
					{ key: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Any placement or migration constraints.' },
				],
			},
			{
				key: 'suspend-site',
				label: 'Suspend site',
				icon: Pause,
				description: 'Suspension is surfaced here, but the actual state transition remains a backend gap.',
				backendSupported: false,
				fields: [
					{ key: 'reason', label: 'Reason', type: 'textarea', placeholder: 'Why is the site being suspended?' },
				],
			},
			{
				key: 'delete-site',
				label: 'Delete site',
				icon: AlertTriangle,
				description: 'Destructive deletion is represented in the UI, but backend execution is not wired in this pass.',
				backendSupported: false,
				fields: [
					{ key: 'confirmation', label: 'Confirmation', type: 'text', placeholder: 'Type DELETE to confirm intent' },
					{ key: 'reason', label: 'Reason', type: 'textarea', placeholder: 'Explain the deletion request.' },
				],
			},
			{
				key: 'backup-site',
				label: 'Backup site',
				icon: CloudDownload,
				description: 'Backup request entry point is present in the UI; backend dispatch remains a gap.',
				backendSupported: false,
				fields: [
					{ key: 'label', label: 'Backup label', type: 'text', placeholder: 'nightly-2026-06-01' },
					{ key: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Retention or restore intent.' },
				],
			},
			{
				key: 'restore-site',
				label: 'Restore site',
				icon: Database,
				description: 'Restore entry point exists in the UI; backend execution is not implemented here.',
				backendSupported: false,
				fields: [
					{ key: 'backup_name', label: 'Backup name', type: 'text', placeholder: 'latest backup label' },
					{ key: 'target_time', label: 'Target time', type: 'text', placeholder: 'optional timestamp' },
					{ key: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Restore intent and constraints.' },
				],
			},
			{
				key: 'upgrade-site',
				label: 'Upgrade site',
				icon: RefreshCcw,
				description: 'Upgrade entry point is a UI-only control until the orchestration backend lands.',
				backendSupported: false,
				fields: [
					{ key: 'target_release', label: 'Target Release', type: 'text', placeholder: 'Release document name' },
					{ key: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Expected impact and timing.' },
				],
			},
			{
				key: 'dns-site',
				label: 'DNS automation',
				icon: CircleHelp,
				description: 'DNS automation is surfaced in the UI, but the workflow backend is a planned gap.',
				backendSupported: false,
				fields: [
					{ key: 'record', label: 'Requested record', type: 'text', placeholder: 'subdomain.example.com' },
					{ key: 'notes', label: 'Notes', type: 'textarea', placeholder: 'DNS lifecycle details.' },
				],
			},
		],
	},
	{
		key: 'regions',
		scope: 'platform',
		label: 'Regions',
		doctype: 'Region',
		route: '/platform/regions',
		detailRoute: (name) => `/platform/regions/${encodeURIComponent(name)}`,
		icon: Globe2,
		listHelp: 'Placement hierarchy for region-aware and environment-aware workflows.',
		tree: {
			parentField: 'parent_region',
			groupField: 'is_group',
			orderBy: 'lft asc',
			extraFields: ['lft', 'rgt'],
		},
		listLimit: 200,
		summaryFields: [
			{ key: 'title', label: 'Title' },
			{ key: 'parent_region', label: 'Parent region', linkPrefix: '/platform/regions/' },
			{ key: 'is_group', label: 'Group' },
		],
		detailFields: [
			{ key: 'name', label: 'Region ID' },
			{ key: 'title', label: 'Title' },
			{ key: 'parent_region', label: 'Parent region', linkPrefix: '/platform/regions/' },
			{ key: 'is_group', label: 'Group' },
		],
		relations: [
			{
				label: 'Customers',
				doctype: 'Customer',
				linkField: 'region',
				sourceField: 'name',
				fields: ['name', 'first_name', 'last_name', 'external_customer_id'],
				route: (name) => `/platform/customers/${encodeURIComponent(name)}`,
			},
			{
				label: 'Benches',
				doctype: 'Bench',
				linkField: 'region',
				sourceField: 'name',
				fields: ['name', 'title', 'release_group', 'privacy'],
				route: (name) => `/platform/benches/${encodeURIComponent(name)}`,
			},
		],
		actions: [],
	},
]

export const platformSettings = {
	key: 'settings',
	scope: 'platform',
	label: 'Platform Settings',
	doctype: 'Platform Settings',
	route: '/platform/settings',
	icon: Settings2,
	editable: true,
	summaryFields: [
		{ key: 'active_cluster_context', label: 'Active cluster/context' },
		{ key: 'operator_namespace', label: 'Operator namespace' },
		{ key: 'default_storage_class', label: 'Default storage class' },
		{ key: 'root_domain', label: 'Root domain' },
		{ key: 'route53_hosted_zone_id', label: 'Route53 hosted zone ID' },
		{ key: 'billing_integration_status', label: 'Billing status' },
		{ key: 'crm_integration_status', label: 'CRM status' },
		{ key: 'support_integration_status', label: 'Support status' },
	],
	detailFields: [
		{ key: 'active_cluster_context', label: 'Active cluster/context' },
		{ key: 'operator_namespace', label: 'Operator namespace' },
		{ key: 'default_storage_class', label: 'Default storage class' },
		{ key: 'default_bench_namespace_pattern', label: 'Default bench namespace pattern' },
		{ key: 'root_domain', label: 'Root domain' },
		{ key: 'route53_hosted_zone_id', label: 'Route53 hosted zone ID' },
		{ key: 'route53_zone_reference', label: 'Route53 zone reference' },
		{ key: 'billing_system', label: 'Billing system' },
		{ key: 'billing_integration_enabled', label: 'Billing integration enabled', type: 'check' },
		{ key: 'billing_integration_status', label: 'Billing integration status' },
		{ key: 'crm_system', label: 'CRM system' },
		{ key: 'crm_integration_enabled', label: 'CRM integration enabled', type: 'check' },
		{ key: 'crm_integration_status', label: 'CRM integration status' },
		{ key: 'support_system', label: 'Support system' },
		{ key: 'support_integration_enabled', label: 'Support integration enabled', type: 'check' },
		{ key: 'support_integration_status', label: 'Support integration status' },
	],
}

export const customerResources = [
	{
		key: 'customer-account',
		scope: 'customer',
		label: 'Account',
		doctype: 'Customer',
		route: '/customer/account',
		icon: UserRound,
		listHelp: 'Your customer identity, region, and external account links.',
		summaryFields: [
			{ key: 'first_name', label: 'First name' },
			{ key: 'last_name', label: 'Last name' },
			{ key: 'region', label: 'Primary region', linkPrefix: '/platform/regions/' },
		],
		detailFields: [
			{ key: 'name', label: 'Customer ID' },
			{ key: 'first_name', label: 'First name' },
			{ key: 'last_name', label: 'Last name' },
			{ key: 'region', label: 'Primary region', linkPrefix: '/platform/regions/' },
			{ key: 'external_customer_id', label: 'External ID' },
		],
		associated: true,
		actions: [
			{
				key: 'request-site',
				label: 'Request site',
				icon: SquareArrowOutUpRight,
				description: 'This entry point collects the request in the UI. Backend creation support is not yet wired.',
				backendSupported: false,
				fields: [
					{ key: 'company_name', label: 'Company name', type: 'text', placeholder: 'Acme Incorporated' },
					{ key: 'preferred_region', label: 'Preferred region', type: 'text', placeholder: 'us-east' },
					{ key: 'preferred_release_group', label: 'Preferred release group', type: 'text', placeholder: '2026.06' },
					{ key: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Describe the request and rollout constraints.' },
				],
			},
		],
	},
	{
			key: 'customer-sites',
		scope: 'customer',
		label: 'Sites',
		doctype: 'Site',
		route: '/customer/sites',
		detailRoute: (name) => `/customer/sites/${encodeURIComponent(name)}`,
		icon: Globe2,
		listHelp: 'Sites linked to your customer record.',
		customerScoped: true,
		summaryFields: [
			{ key: 'title', label: 'Title' },
			{ key: 'domain', label: 'Domain' },
			{ key: 'site_status', label: 'Site status' },
			{ key: 'provisioning_status', label: 'Provisioning' },
			{ key: 'bench', label: 'Bench', linkPrefix: '/platform/benches/' },
		],
		detailFields: [
			{ key: 'name', label: 'Site ID' },
			{ key: 'title', label: 'Title' },
			{ key: 'domain', label: 'Domain' },
			{ key: 'site_status', label: 'Site status' },
			{ key: 'provisioning_status', label: 'Provisioning status' },
			{ key: 'dns_status', label: 'DNS status' },
			{ key: 'backup_state', label: 'Backup state' },
			{ key: 'restore_state', label: 'Restore state' },
			{ key: 'upgrade_state', label: 'Upgrade state' },
		],
		relations: [
			{
				label: 'Bench',
				doctype: 'Bench',
				linkField: 'name',
				sourceField: 'bench',
				fields: ['name', 'title', 'release_group', 'region'],
				route: (name) => `/platform/benches/${encodeURIComponent(name)}`,
			},
		],
		actions: [
			{
				key: 'request-site',
				label: 'Request site',
				icon: SquareArrowOutUpRight,
				description: 'Create requests are captured in the UI first while backend orchestration remains pending.',
				backendSupported: false,
				fields: [
					{ key: 'company_name', label: 'Company name', type: 'text', placeholder: 'Acme Incorporated' },
					{ key: 'preferred_region', label: 'Preferred region', type: 'text', placeholder: 'us-east' },
					{ key: 'preferred_release_group', label: 'Preferred release group', type: 'text', placeholder: '2026.06' },
					{ key: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Describe the request and rollout constraints.' },
				],
			},
		],
	},
]

export const platformNav = [
	{
		heading: 'Platform console',
		items: [
			{ key: 'platform-dashboard', label: 'Dashboard', note: 'System status and record shortcuts', route: '/platform/dashboard', icon: LayoutDashboard },
			{ key: 'platform-customers', label: 'Customers', note: 'Identity and access', route: '/platform/customers', icon: Users },
			{ key: 'platform-release-groups', label: 'Release Groups', note: 'Image family master data', route: '/platform/release-groups', icon: Layers3 },
			{ key: 'platform-apps', label: 'Apps', note: 'Included app master data', route: '/platform/apps', icon: Package },
			{ key: 'platform-releases', label: 'Releases', note: 'Deployable versions', route: '/platform/releases', icon: GitBranch },
			{ key: 'platform-benches', label: 'Benches', note: 'Runtime grouping', route: '/platform/benches', icon: Server },
			{ key: 'platform-sites', label: 'Sites', note: 'Tenant instances', route: '/platform/sites', icon: Globe2 },
			{ key: 'platform-regions', label: 'Regions', note: 'Placement hierarchy', route: '/platform/regions', icon: Globe2 },
			{ key: 'platform-settings', label: 'Platform Settings', note: 'DNS and integrations', route: '/platform/settings', icon: Settings2 },
		],
	},
]

export const customerNav = [
	{
		heading: 'Customer portal',
		items: [
			{ key: 'customer-dashboard', label: 'Dashboard', note: 'Site status and next steps', route: '/customer/dashboard', icon: LayoutDashboard },
			{ key: 'customer-sites', label: 'Sites', note: 'Manage tenant instances', route: '/customer/sites', icon: Globe2 },
			{ key: 'customer-create-site', label: 'Create Site', note: 'Start a new site request', route: '/customer/create-site', icon: SquareArrowOutUpRight },
			{ key: 'customer-account', label: 'Account', note: 'Identity and region', route: '/customer/account', icon: UserRound },
		],
	},
]

export function getResourceByKey(key) {
	return [...platformResources, ...customerResources].find((resource) => resource.key === key) || null
}

export function getRoutesForScope(scope) {
	return scope === 'customer' ? customerNav : platformNav
}

export function getHomeRoute(session) {
	if (session?.canAccessPlatform) {
		return '/platform/dashboard'
	}

	return '/customer/dashboard'
}
